#pragma once
/*=================================================
* Copyright © 2020-2026 ChivenZhang.
* All Rights Reserved.
* =====================Note=========================
*
*
* ====================History=======================
* Created by chivenzhang@gmail.com.
*
* =================================================*/

typedef enum {
    UI_CSS_UNIT__UNDEF      = 0x0000,
    UI_CSS_UNIT__LAST_ENTRY = 0x0022
}
ui_css_unit_t;

typedef enum {
    UI_CSS_UNIT_ABSOLUTE__BEGIN      = 0x0001,
    UI_CSS_UNIT_Q                    = 0x0001,
    UI_CSS_UNIT_CM                   = 0x0002,
    UI_CSS_UNIT_IN                   = 0x0003,
    UI_CSS_UNIT_MM                   = 0x0004,
    UI_CSS_UNIT_PC                   = 0x0005,
    UI_CSS_UNIT_PT                   = 0x0006,
    UI_CSS_UNIT_PX                   = 0x0007,
    UI_CSS_UNIT_ABSOLUTE__LAST_ENTRY = 0x0008
}
ui_css_unit_absolute_t;

typedef enum {
    UI_CSS_UNIT_RELATIVE__BEGIN      = 0x0008,
    UI_CSS_UNIT_CAP                  = 0x0008,
    UI_CSS_UNIT_CH                   = 0x0009,
    UI_CSS_UNIT_EM                   = 0x000a,
    UI_CSS_UNIT_EX                   = 0x000b,
    UI_CSS_UNIT_IC                   = 0x000c,
    UI_CSS_UNIT_LH                   = 0x000d,
    UI_CSS_UNIT_REM                  = 0x000e,
    UI_CSS_UNIT_RLH                  = 0x000f,
    UI_CSS_UNIT_VB                   = 0x0010,
    UI_CSS_UNIT_VH                   = 0x0011,
    UI_CSS_UNIT_VI                   = 0x0012,
    UI_CSS_UNIT_VMAX                 = 0x0013,
    UI_CSS_UNIT_VMIN                 = 0x0014,
    UI_CSS_UNIT_VW                   = 0x0015,
    UI_CSS_UNIT_RELATIVE__LAST_ENTRY = 0x0016
}
ui_css_unit_relative_t;

typedef enum {
    UI_CSS_UNIT_ANGLE__BEGIN      = 0x0016,
    UI_CSS_UNIT_DEG               = 0x0016,
    UI_CSS_UNIT_GRAD              = 0x0017,
    UI_CSS_UNIT_RAD               = 0x0018,
    UI_CSS_UNIT_TURN              = 0x0019,
    UI_CSS_UNIT_ANGLE__LAST_ENTRY = 0x001a
}
ui_css_unit_angle_t;

typedef enum {
    UI_CSS_UNIT_FREQUENCY__BEGIN      = 0x001a,
    UI_CSS_UNIT_HZ                    = 0x001a,
    UI_CSS_UNIT_KHZ                   = 0x001b,
    UI_CSS_UNIT_FREQUENCY__LAST_ENTRY = 0x001c
}
ui_css_unit_frequency_t;

typedef enum {
    UI_CSS_UNIT_RESOLUTION__BEGIN      = 0x001c,
    UI_CSS_UNIT_DPCM                   = 0x001c,
    UI_CSS_UNIT_DPI                    = 0x001d,
    UI_CSS_UNIT_DPPX                   = 0x001e,
    UI_CSS_UNIT_X                      = 0x001f,
    UI_CSS_UNIT_RESOLUTION__LAST_ENTRY = 0x0020
}
ui_css_unit_resolution_t;

typedef enum {
    UI_CSS_UNIT_DURATION__BEGIN      = 0x0020,
    UI_CSS_UNIT_MS                   = 0x0020,
    UI_CSS_UNIT_S                    = 0x0021,
    UI_CSS_UNIT_DURATION__LAST_ENTRY = 0x0022
}
ui_css_unit_duration_t;

enum {
    UI_CSS_VALUE__UNDEF               = 0x0000,
    UI_CSS_VALUE_INITIAL              = 0x0001,
    UI_CSS_VALUE_INHERIT              = 0x0002,
    UI_CSS_VALUE_UNSET                = 0x0003,
    UI_CSS_VALUE_REVERT               = 0x0004,
    UI_CSS_VALUE_FLEX_START           = 0x0005,
    UI_CSS_VALUE_FLEX_END             = 0x0006,
    UI_CSS_VALUE_CENTER               = 0x0007,
    UI_CSS_VALUE_SPACE_BETWEEN        = 0x0008,
    UI_CSS_VALUE_SPACE_AROUND         = 0x0009,
    UI_CSS_VALUE_STRETCH              = 0x000a,
    UI_CSS_VALUE_BASELINE             = 0x000b,
    UI_CSS_VALUE_AUTO                 = 0x000c,
    UI_CSS_VALUE_TEXT_BOTTOM          = 0x000d,
    UI_CSS_VALUE_ALPHABETIC           = 0x000e,
    UI_CSS_VALUE_IDEOGRAPHIC          = 0x000f,
    UI_CSS_VALUE_MIDDLE               = 0x0010,
    UI_CSS_VALUE_CENTRAL              = 0x0011,
    UI_CSS_VALUE_MATHEMATICAL         = 0x0012,
    UI_CSS_VALUE_TEXT_TOP             = 0x0013,
    UI_CSS_VALUE__LENGTH              = 0x0014,
    UI_CSS_VALUE__PERCENTAGE          = 0x0015,
    UI_CSS_VALUE_SUB                  = 0x0016,
    UI_CSS_VALUE_SUPER                = 0x0017,
    UI_CSS_VALUE_TOP                  = 0x0018,
    UI_CSS_VALUE_BOTTOM               = 0x0019,
    UI_CSS_VALUE_FIRST                = 0x001a,
    UI_CSS_VALUE_LAST                 = 0x001b,
    UI_CSS_VALUE_THIN                 = 0x001c,
    UI_CSS_VALUE_MEDIUM               = 0x001d,
    UI_CSS_VALUE_THICK                = 0x001e,
    UI_CSS_VALUE_NONE                 = 0x001f,
    UI_CSS_VALUE_HIDDEN               = 0x0020,
    UI_CSS_VALUE_DOTTED               = 0x0021,
    UI_CSS_VALUE_DASHED               = 0x0022,
    UI_CSS_VALUE_SOLID                = 0x0023,
    UI_CSS_VALUE_DOUBLE               = 0x0024,
    UI_CSS_VALUE_GROOVE               = 0x0025,
    UI_CSS_VALUE_RIDGE                = 0x0026,
    UI_CSS_VALUE_INSET                = 0x0027,
    UI_CSS_VALUE_OUTSET               = 0x0028,
    UI_CSS_VALUE_CONTENT_BOX          = 0x0029,
    UI_CSS_VALUE_BORDER_BOX           = 0x002a,
    UI_CSS_VALUE_INLINE_START         = 0x002b,
    UI_CSS_VALUE_INLINE_END           = 0x002c,
    UI_CSS_VALUE_BLOCK_START          = 0x002d,
    UI_CSS_VALUE_BLOCK_END            = 0x002e,
    UI_CSS_VALUE_LEFT                 = 0x002f,
    UI_CSS_VALUE_RIGHT                = 0x0030,
    UI_CSS_VALUE_CURRENTCOLOR         = 0x0031,
    UI_CSS_VALUE_TRANSPARENT          = 0x0032,
    UI_CSS_VALUE_HEX                  = 0x0033,
    UI_CSS_VALUE_ALICEBLUE            = 0x0034,
    UI_CSS_VALUE_ANTIQUEWHITE         = 0x0035,
    UI_CSS_VALUE_AQUA                 = 0x0036,
    UI_CSS_VALUE_AQUAMARINE           = 0x0037,
    UI_CSS_VALUE_AZURE                = 0x0038,
    UI_CSS_VALUE_BEIGE                = 0x0039,
    UI_CSS_VALUE_BISQUE               = 0x003a,
    UI_CSS_VALUE_BLACK                = 0x003b,
    UI_CSS_VALUE_BLANCHEDALMOND       = 0x003c,
    UI_CSS_VALUE_BLUE                 = 0x003d,
    UI_CSS_VALUE_BLUEVIOLET           = 0x003e,
    UI_CSS_VALUE_BROWN                = 0x003f,
    UI_CSS_VALUE_BURLYWOOD            = 0x0040,
    UI_CSS_VALUE_CADETBLUE            = 0x0041,
    UI_CSS_VALUE_CHARTREUSE           = 0x0042,
    UI_CSS_VALUE_CHOCOLATE            = 0x0043,
    UI_CSS_VALUE_CORAL                = 0x0044,
    UI_CSS_VALUE_CORNFLOWERBLUE       = 0x0045,
    UI_CSS_VALUE_CORNSILK             = 0x0046,
    UI_CSS_VALUE_CRIMSON              = 0x0047,
    UI_CSS_VALUE_CYAN                 = 0x0048,
    UI_CSS_VALUE_DARKBLUE             = 0x0049,
    UI_CSS_VALUE_DARKCYAN             = 0x004a,
    UI_CSS_VALUE_DARKGOLDENROD        = 0x004b,
    UI_CSS_VALUE_DARKGRAY             = 0x004c,
    UI_CSS_VALUE_DARKGREEN            = 0x004d,
    UI_CSS_VALUE_DARKGREY             = 0x004e,
    UI_CSS_VALUE_DARKKHAKI            = 0x004f,
    UI_CSS_VALUE_DARKMAGENTA          = 0x0050,
    UI_CSS_VALUE_DARKOLIVEGREEN       = 0x0051,
    UI_CSS_VALUE_DARKORANGE           = 0x0052,
    UI_CSS_VALUE_DARKORCHID           = 0x0053,
    UI_CSS_VALUE_DARKRED              = 0x0054,
    UI_CSS_VALUE_DARKSALMON           = 0x0055,
    UI_CSS_VALUE_DARKSEAGREEN         = 0x0056,
    UI_CSS_VALUE_DARKSLATEBLUE        = 0x0057,
    UI_CSS_VALUE_DARKSLATEGRAY        = 0x0058,
    UI_CSS_VALUE_DARKSLATEGREY        = 0x0059,
    UI_CSS_VALUE_DARKTURQUOISE        = 0x005a,
    UI_CSS_VALUE_DARKVIOLET           = 0x005b,
    UI_CSS_VALUE_DEEPPINK             = 0x005c,
    UI_CSS_VALUE_DEEPSKYBLUE          = 0x005d,
    UI_CSS_VALUE_DIMGRAY              = 0x005e,
    UI_CSS_VALUE_DIMGREY              = 0x005f,
    UI_CSS_VALUE_DODGERBLUE           = 0x0060,
    UI_CSS_VALUE_FIREBRICK            = 0x0061,
    UI_CSS_VALUE_FLORALWHITE          = 0x0062,
    UI_CSS_VALUE_FORESTGREEN          = 0x0063,
    UI_CSS_VALUE_FUCHSIA              = 0x0064,
    UI_CSS_VALUE_GAINSBORO            = 0x0065,
    UI_CSS_VALUE_GHOSTWHITE           = 0x0066,
    UI_CSS_VALUE_GOLD                 = 0x0067,
    UI_CSS_VALUE_GOLDENROD            = 0x0068,
    UI_CSS_VALUE_GRAY                 = 0x0069,
    UI_CSS_VALUE_GREEN                = 0x006a,
    UI_CSS_VALUE_GREENYELLOW          = 0x006b,
    UI_CSS_VALUE_GREY                 = 0x006c,
    UI_CSS_VALUE_HONEYDEW             = 0x006d,
    UI_CSS_VALUE_HOTPINK              = 0x006e,
    UI_CSS_VALUE_INDIANRED            = 0x006f,
    UI_CSS_VALUE_INDIGO               = 0x0070,
    UI_CSS_VALUE_IVORY                = 0x0071,
    UI_CSS_VALUE_KHAKI                = 0x0072,
    UI_CSS_VALUE_LAVENDER             = 0x0073,
    UI_CSS_VALUE_LAVENDERBLUSH        = 0x0074,
    UI_CSS_VALUE_LAWNGREEN            = 0x0075,
    UI_CSS_VALUE_LEMONCHIFFON         = 0x0076,
    UI_CSS_VALUE_LIGHTBLUE            = 0x0077,
    UI_CSS_VALUE_LIGHTCORAL           = 0x0078,
    UI_CSS_VALUE_LIGHTCYAN            = 0x0079,
    UI_CSS_VALUE_LIGHTGOLDENRODYELLOW = 0x007a,
    UI_CSS_VALUE_LIGHTGRAY            = 0x007b,
    UI_CSS_VALUE_LIGHTGREEN           = 0x007c,
    UI_CSS_VALUE_LIGHTGREY            = 0x007d,
    UI_CSS_VALUE_LIGHTPINK            = 0x007e,
    UI_CSS_VALUE_LIGHTSALMON          = 0x007f,
    UI_CSS_VALUE_LIGHTSEAGREEN        = 0x0080,
    UI_CSS_VALUE_LIGHTSKYBLUE         = 0x0081,
    UI_CSS_VALUE_LIGHTSLATEGRAY       = 0x0082,
    UI_CSS_VALUE_LIGHTSLATEGREY       = 0x0083,
    UI_CSS_VALUE_LIGHTSTEELBLUE       = 0x0084,
    UI_CSS_VALUE_LIGHTYELLOW          = 0x0085,
    UI_CSS_VALUE_LIME                 = 0x0086,
    UI_CSS_VALUE_LIMEGREEN            = 0x0087,
    UI_CSS_VALUE_LINEN                = 0x0088,
    UI_CSS_VALUE_MAGENTA              = 0x0089,
    UI_CSS_VALUE_MAROON               = 0x008a,
    UI_CSS_VALUE_MEDIUMAQUAMARINE     = 0x008b,
    UI_CSS_VALUE_MEDIUMBLUE           = 0x008c,
    UI_CSS_VALUE_MEDIUMORCHID         = 0x008d,
    UI_CSS_VALUE_MEDIUMPURPLE         = 0x008e,
    UI_CSS_VALUE_MEDIUMSEAGREEN       = 0x008f,
    UI_CSS_VALUE_MEDIUMSLATEBLUE      = 0x0090,
    UI_CSS_VALUE_MEDIUMSPRINGGREEN    = 0x0091,
    UI_CSS_VALUE_MEDIUMTURQUOISE      = 0x0092,
    UI_CSS_VALUE_MEDIUMVIOLETRED      = 0x0093,
    UI_CSS_VALUE_MIDNIGHTBLUE         = 0x0094,
    UI_CSS_VALUE_MINTCREAM            = 0x0095,
    UI_CSS_VALUE_MISTYROSE            = 0x0096,
    UI_CSS_VALUE_MOCCASIN             = 0x0097,
    UI_CSS_VALUE_NAVAJOWHITE          = 0x0098,
    UI_CSS_VALUE_NAVY                 = 0x0099,
    UI_CSS_VALUE_OLDLACE              = 0x009a,
    UI_CSS_VALUE_OLIVE                = 0x009b,
    UI_CSS_VALUE_OLIVEDRAB            = 0x009c,
    UI_CSS_VALUE_ORANGE               = 0x009d,
    UI_CSS_VALUE_ORANGERED            = 0x009e,
    UI_CSS_VALUE_ORCHID               = 0x009f,
    UI_CSS_VALUE_PALEGOLDENROD        = 0x00a0,
    UI_CSS_VALUE_PALEGREEN            = 0x00a1,
    UI_CSS_VALUE_PALETURQUOISE        = 0x00a2,
    UI_CSS_VALUE_PALEVIOLETRED        = 0x00a3,
    UI_CSS_VALUE_PAPAYAWHIP           = 0x00a4,
    UI_CSS_VALUE_PEACHPUFF            = 0x00a5,
    UI_CSS_VALUE_PERU                 = 0x00a6,
    UI_CSS_VALUE_PINK                 = 0x00a7,
    UI_CSS_VALUE_PLUM                 = 0x00a8,
    UI_CSS_VALUE_POWDERBLUE           = 0x00a9,
    UI_CSS_VALUE_PURPLE               = 0x00aa,
    UI_CSS_VALUE_REBECCAPURPLE        = 0x00ab,
    UI_CSS_VALUE_RED                  = 0x00ac,
    UI_CSS_VALUE_ROSYBROWN            = 0x00ad,
    UI_CSS_VALUE_ROYALBLUE            = 0x00ae,
    UI_CSS_VALUE_SADDLEBROWN          = 0x00af,
    UI_CSS_VALUE_SALMON               = 0x00b0,
    UI_CSS_VALUE_SANDYBROWN           = 0x00b1,
    UI_CSS_VALUE_SEAGREEN             = 0x00b2,
    UI_CSS_VALUE_SEASHELL             = 0x00b3,
    UI_CSS_VALUE_SIENNA               = 0x00b4,
    UI_CSS_VALUE_SILVER               = 0x00b5,
    UI_CSS_VALUE_SKYBLUE              = 0x00b6,
    UI_CSS_VALUE_SLATEBLUE            = 0x00b7,
    UI_CSS_VALUE_SLATEGRAY            = 0x00b8,
    UI_CSS_VALUE_SLATEGREY            = 0x00b9,
    UI_CSS_VALUE_SNOW                 = 0x00ba,
    UI_CSS_VALUE_SPRINGGREEN          = 0x00bb,
    UI_CSS_VALUE_STEELBLUE            = 0x00bc,
    UI_CSS_VALUE_TAN                  = 0x00bd,
    UI_CSS_VALUE_TEAL                 = 0x00be,
    UI_CSS_VALUE_THISTLE              = 0x00bf,
    UI_CSS_VALUE_TOMATO               = 0x00c0,
    UI_CSS_VALUE_TURQUOISE            = 0x00c1,
    UI_CSS_VALUE_VIOLET               = 0x00c2,
    UI_CSS_VALUE_WHEAT                = 0x00c3,
    UI_CSS_VALUE_WHITE                = 0x00c4,
    UI_CSS_VALUE_WHITESMOKE           = 0x00c5,
    UI_CSS_VALUE_YELLOW               = 0x00c6,
    UI_CSS_VALUE_YELLOWGREEN          = 0x00c7,
    UI_CSS_VALUE_CANVAS               = 0x00c8,
    UI_CSS_VALUE_CANVASTEXT           = 0x00c9,
    UI_CSS_VALUE_LINKTEXT             = 0x00ca,
    UI_CSS_VALUE_VISITEDTEXT          = 0x00cb,
    UI_CSS_VALUE_ACTIVETEXT           = 0x00cc,
    UI_CSS_VALUE_BUTTONFACE           = 0x00cd,
    UI_CSS_VALUE_BUTTONTEXT           = 0x00ce,
    UI_CSS_VALUE_BUTTONBORDER         = 0x00cf,
    UI_CSS_VALUE_FIELD                = 0x00d0,
    UI_CSS_VALUE_FIELDTEXT            = 0x00d1,
    UI_CSS_VALUE_HIGHLIGHT            = 0x00d2,
    UI_CSS_VALUE_HIGHLIGHTTEXT        = 0x00d3,
    UI_CSS_VALUE_SELECTEDITEM         = 0x00d4,
    UI_CSS_VALUE_SELECTEDITEMTEXT     = 0x00d5,
    UI_CSS_VALUE_MARK                 = 0x00d6,
    UI_CSS_VALUE_MARKTEXT             = 0x00d7,
    UI_CSS_VALUE_GRAYTEXT             = 0x00d8,
    UI_CSS_VALUE_ACCENTCOLOR          = 0x00d9,
    UI_CSS_VALUE_ACCENTCOLORTEXT      = 0x00da,
    UI_CSS_VALUE_RGB                  = 0x00db,
    UI_CSS_VALUE_RGBA                 = 0x00dc,
    UI_CSS_VALUE_HSL                  = 0x00dd,
    UI_CSS_VALUE_HSLA                 = 0x00de,
    UI_CSS_VALUE_HWB                  = 0x00df,
    UI_CSS_VALUE_LAB                  = 0x00e0,
    UI_CSS_VALUE_LCH                  = 0x00e1,
    UI_CSS_VALUE_OKLAB                = 0x00e2,
    UI_CSS_VALUE_OKLCH                = 0x00e3,
    UI_CSS_VALUE_COLOR                = 0x00e4,
    UI_CSS_VALUE_LTR                  = 0x00e5,
    UI_CSS_VALUE_RTL                  = 0x00e6,
    UI_CSS_VALUE_BLOCK                = 0x00e7,
    UI_CSS_VALUE_INLINE               = 0x00e8,
    UI_CSS_VALUE_RUN_IN               = 0x00e9,
    UI_CSS_VALUE_FLOW                 = 0x00ea,
    UI_CSS_VALUE_FLOW_ROOT            = 0x00eb,
    UI_CSS_VALUE_TABLE                = 0x00ec,
    UI_CSS_VALUE_FLEX                 = 0x00ed,
    UI_CSS_VALUE_GRID                 = 0x00ee,
    UI_CSS_VALUE_RUBY                 = 0x00ef,
    UI_CSS_VALUE_LIST_ITEM            = 0x00f0,
    UI_CSS_VALUE_TABLE_ROW_GROUP      = 0x00f1,
    UI_CSS_VALUE_TABLE_HEADER_GROUP   = 0x00f2,
    UI_CSS_VALUE_TABLE_FOOTER_GROUP   = 0x00f3,
    UI_CSS_VALUE_TABLE_ROW            = 0x00f4,
    UI_CSS_VALUE_TABLE_CELL           = 0x00f5,
    UI_CSS_VALUE_TABLE_COLUMN_GROUP   = 0x00f6,
    UI_CSS_VALUE_TABLE_COLUMN         = 0x00f7,
    UI_CSS_VALUE_TABLE_CAPTION        = 0x00f8,
    UI_CSS_VALUE_RUBY_BASE            = 0x00f9,
    UI_CSS_VALUE_RUBY_TEXT            = 0x00fa,
    UI_CSS_VALUE_RUBY_BASE_CONTAINER  = 0x00fb,
    UI_CSS_VALUE_RUBY_TEXT_CONTAINER  = 0x00fc,
    UI_CSS_VALUE_CONTENTS             = 0x00fd,
    UI_CSS_VALUE_INLINE_BLOCK         = 0x00fe,
    UI_CSS_VALUE_INLINE_TABLE         = 0x00ff,
    UI_CSS_VALUE_INLINE_FLEX          = 0x0100,
    UI_CSS_VALUE_INLINE_GRID          = 0x0101,
    UI_CSS_VALUE_HANGING              = 0x0102,
    UI_CSS_VALUE_CONTENT              = 0x0103,
    UI_CSS_VALUE_ROW                  = 0x0104,
    UI_CSS_VALUE_ROW_REVERSE          = 0x0105,
    UI_CSS_VALUE_COLUMN               = 0x0106,
    UI_CSS_VALUE_COLUMN_REVERSE       = 0x0107,
    UI_CSS_VALUE__NUMBER              = 0x0108,
    UI_CSS_VALUE_NOWRAP               = 0x0109,
    UI_CSS_VALUE_WRAP                 = 0x010a,
    UI_CSS_VALUE_WRAP_REVERSE         = 0x010b,
    UI_CSS_VALUE_SNAP_BLOCK           = 0x010c,
    UI_CSS_VALUE_START                = 0x010d,
    UI_CSS_VALUE_END                  = 0x010e,
    UI_CSS_VALUE_NEAR                 = 0x010f,
    UI_CSS_VALUE_SNAP_INLINE          = 0x0110,
    UI_CSS_VALUE__INTEGER             = 0x0111,
    UI_CSS_VALUE_REGION               = 0x0112,
    UI_CSS_VALUE_PAGE                 = 0x0113,
    UI_CSS_VALUE_SERIF                = 0x0114,
    UI_CSS_VALUE_SANS_SERIF           = 0x0115,
    UI_CSS_VALUE_CURSIVE              = 0x0116,
    UI_CSS_VALUE_FANTASY              = 0x0117,
    UI_CSS_VALUE_MONOSPACE            = 0x0118,
    UI_CSS_VALUE_SYSTEM_UI            = 0x0119,
    UI_CSS_VALUE_EMOJI                = 0x011a,
    UI_CSS_VALUE_MATH                 = 0x011b,
    UI_CSS_VALUE_FANGSONG             = 0x011c,
    UI_CSS_VALUE_UI_SERIF             = 0x011d,
    UI_CSS_VALUE_UI_SANS_SERIF        = 0x011e,
    UI_CSS_VALUE_UI_MONOSPACE         = 0x011f,
    UI_CSS_VALUE_UI_ROUNDED           = 0x0120,
    UI_CSS_VALUE_XX_SMALL             = 0x0121,
    UI_CSS_VALUE_X_SMALL              = 0x0122,
    UI_CSS_VALUE_SMALL                = 0x0123,
    UI_CSS_VALUE_LARGE                = 0x0124,
    UI_CSS_VALUE_X_LARGE              = 0x0125,
    UI_CSS_VALUE_XX_LARGE             = 0x0126,
    UI_CSS_VALUE_XXX_LARGE            = 0x0127,
    UI_CSS_VALUE_LARGER               = 0x0128,
    UI_CSS_VALUE_SMALLER              = 0x0129,
    UI_CSS_VALUE_NORMAL               = 0x012a,
    UI_CSS_VALUE_ULTRA_CONDENSED      = 0x012b,
    UI_CSS_VALUE_EXTRA_CONDENSED      = 0x012c,
    UI_CSS_VALUE_CONDENSED            = 0x012d,
    UI_CSS_VALUE_SEMI_CONDENSED       = 0x012e,
    UI_CSS_VALUE_SEMI_EXPANDED        = 0x012f,
    UI_CSS_VALUE_EXPANDED             = 0x0130,
    UI_CSS_VALUE_EXTRA_EXPANDED       = 0x0131,
    UI_CSS_VALUE_ULTRA_EXPANDED       = 0x0132,
    UI_CSS_VALUE_ITALIC               = 0x0133,
    UI_CSS_VALUE_OBLIQUE              = 0x0134,
    UI_CSS_VALUE_BOLD                 = 0x0135,
    UI_CSS_VALUE_BOLDER               = 0x0136,
    UI_CSS_VALUE_LIGHTER              = 0x0137,
    UI_CSS_VALUE_FORCE_END            = 0x0138,
    UI_CSS_VALUE_ALLOW_END            = 0x0139,
    UI_CSS_VALUE_MIN_CONTENT          = 0x013a,
    UI_CSS_VALUE_MAX_CONTENT          = 0x013b,
    UI_CSS_VALUE__ANGLE               = 0x013c,
    UI_CSS_VALUE_MANUAL               = 0x013d,
    UI_CSS_VALUE_LOOSE                = 0x013e,
    UI_CSS_VALUE_STRICT               = 0x013f,
    UI_CSS_VALUE_ANYWHERE             = 0x0140,
    UI_CSS_VALUE_VISIBLE              = 0x0141,
    UI_CSS_VALUE_CLIP                 = 0x0142,
    UI_CSS_VALUE_SCROLL               = 0x0143,
    UI_CSS_VALUE_BREAK_WORD           = 0x0144,
    UI_CSS_VALUE_STATIC               = 0x0145,
    UI_CSS_VALUE_RELATIVE             = 0x0146,
    UI_CSS_VALUE_ABSOLUTE             = 0x0147,
    UI_CSS_VALUE_STICKY               = 0x0148,
    UI_CSS_VALUE_FIXED                = 0x0149,
    UI_CSS_VALUE_JUSTIFY              = 0x014a,
    UI_CSS_VALUE_MATCH_PARENT         = 0x014b,
    UI_CSS_VALUE_JUSTIFY_ALL          = 0x014c,
    UI_CSS_VALUE_ALL                  = 0x014d,
    UI_CSS_VALUE_DIGITS               = 0x014e,
    UI_CSS_VALUE_UNDERLINE            = 0x014f,
    UI_CSS_VALUE_OVERLINE             = 0x0150,
    UI_CSS_VALUE_LINE_THROUGH         = 0x0151,
    UI_CSS_VALUE_BLINK                = 0x0152,
    UI_CSS_VALUE_WAVY                 = 0x0153,
    UI_CSS_VALUE_EACH_LINE            = 0x0154,
    UI_CSS_VALUE_INTER_WORD           = 0x0155,
    UI_CSS_VALUE_INTER_CHARACTER      = 0x0156,
    UI_CSS_VALUE_MIXED                = 0x0157,
    UI_CSS_VALUE_UPRIGHT              = 0x0158,
    UI_CSS_VALUE_SIDEWAYS             = 0x0159,
    UI_CSS_VALUE_ELLIPSIS             = 0x015a,
    UI_CSS_VALUE_CAPITALIZE           = 0x015b,
    UI_CSS_VALUE_UPPERCASE            = 0x015c,
    UI_CSS_VALUE_LOWERCASE            = 0x015d,
    UI_CSS_VALUE_FULL_WIDTH           = 0x015e,
    UI_CSS_VALUE_FULL_SIZE_KANA       = 0x015f,
    UI_CSS_VALUE_EMBED                = 0x0160,
    UI_CSS_VALUE_ISOLATE              = 0x0161,
    UI_CSS_VALUE_BIDI_OVERRIDE        = 0x0162,
    UI_CSS_VALUE_ISOLATE_OVERRIDE     = 0x0163,
    UI_CSS_VALUE_PLAINTEXT            = 0x0164,
    UI_CSS_VALUE_COLLAPSE             = 0x0165,
    UI_CSS_VALUE_PRE                  = 0x0166,
    UI_CSS_VALUE_PRE_WRAP             = 0x0167,
    UI_CSS_VALUE_BREAK_SPACES         = 0x0168,
    UI_CSS_VALUE_PRE_LINE             = 0x0169,
    UI_CSS_VALUE_KEEP_ALL             = 0x016a,
    UI_CSS_VALUE_BREAK_ALL            = 0x016b,
    UI_CSS_VALUE_BOTH                 = 0x016c,
    UI_CSS_VALUE_MINIMUM              = 0x016d,
    UI_CSS_VALUE_MAXIMUM              = 0x016e,
    UI_CSS_VALUE_CLEAR                = 0x016f,
    UI_CSS_VALUE_HORIZONTAL_TB        = 0x0170,
    UI_CSS_VALUE_VERTICAL_RL          = 0x0171,
    UI_CSS_VALUE_VERTICAL_LR          = 0x0172,
    UI_CSS_VALUE_SIDEWAYS_RL          = 0x0173,
    UI_CSS_VALUE_SIDEWAYS_LR          = 0x0174,
    UI_CSS_VALUE__LAST_ENTRY          = 0x0175
};
typedef unsigned int ui_css_value_type_t;

enum {
    UI_CSS_PROPERTY__UNDEF                = 0x0000,
    UI_CSS_PROPERTY__CUSTOM               = 0x0001,
    UI_CSS_PROPERTY_ALIGN_CONTENT         = 0x0002,
    UI_CSS_PROPERTY_ALIGN_ITEMS           = 0x0003,
    UI_CSS_PROPERTY_ALIGN_SELF            = 0x0004,
    UI_CSS_PROPERTY_ALIGNMENT_BASELINE    = 0x0005,
    UI_CSS_PROPERTY_BACKGROUND_COLOR      = 0x0006,
    UI_CSS_PROPERTY_BASELINE_SHIFT        = 0x0007,
    UI_CSS_PROPERTY_BASELINE_SOURCE       = 0x0008,
    UI_CSS_PROPERTY_BORDER                = 0x0009,
    UI_CSS_PROPERTY_BORDER_BOTTOM         = 0x000a,
    UI_CSS_PROPERTY_BORDER_BOTTOM_COLOR   = 0x000b,
    UI_CSS_PROPERTY_BORDER_LEFT           = 0x000c,
    UI_CSS_PROPERTY_BORDER_LEFT_COLOR     = 0x000d,
    UI_CSS_PROPERTY_BORDER_RIGHT          = 0x000e,
    UI_CSS_PROPERTY_BORDER_RIGHT_COLOR    = 0x000f,
    UI_CSS_PROPERTY_BORDER_TOP            = 0x0010,
    UI_CSS_PROPERTY_BORDER_TOP_COLOR      = 0x0011,
    UI_CSS_PROPERTY_BOTTOM                = 0x0012,
    UI_CSS_PROPERTY_BOX_SIZING            = 0x0013,
    UI_CSS_PROPERTY_CLEAR                 = 0x0014,
    UI_CSS_PROPERTY_COLOR                 = 0x0015,
    UI_CSS_PROPERTY_DIRECTION             = 0x0016,
    UI_CSS_PROPERTY_DISPLAY               = 0x0017,
    UI_CSS_PROPERTY_DOMINANT_BASELINE     = 0x0018,
    UI_CSS_PROPERTY_FLEX                  = 0x0019,
    UI_CSS_PROPERTY_FLEX_BASIS            = 0x001a,
    UI_CSS_PROPERTY_FLEX_DIRECTION        = 0x001b,
    UI_CSS_PROPERTY_FLEX_FLOW             = 0x001c,
    UI_CSS_PROPERTY_FLEX_GROW             = 0x001d,
    UI_CSS_PROPERTY_FLEX_SHRINK           = 0x001e,
    UI_CSS_PROPERTY_FLEX_WRAP             = 0x001f,
    UI_CSS_PROPERTY_FLOAT                 = 0x0020,
    UI_CSS_PROPERTY_FLOAT_DEFER           = 0x0021,
    UI_CSS_PROPERTY_FLOAT_OFFSET          = 0x0022,
    UI_CSS_PROPERTY_FLOAT_REFERENCE       = 0x0023,
    UI_CSS_PROPERTY_FONT_FAMILY           = 0x0024,
    UI_CSS_PROPERTY_FONT_SIZE             = 0x0025,
    UI_CSS_PROPERTY_FONT_STRETCH          = 0x0026,
    UI_CSS_PROPERTY_FONT_STYLE            = 0x0027,
    UI_CSS_PROPERTY_FONT_WEIGHT           = 0x0028,
    UI_CSS_PROPERTY_HANGING_PUNCTUATION   = 0x0029,
    UI_CSS_PROPERTY_HEIGHT                = 0x002a,
    UI_CSS_PROPERTY_HYPHENS               = 0x002b,
    UI_CSS_PROPERTY_INSET_BLOCK_END       = 0x002c,
    UI_CSS_PROPERTY_INSET_BLOCK_START     = 0x002d,
    UI_CSS_PROPERTY_INSET_INLINE_END      = 0x002e,
    UI_CSS_PROPERTY_INSET_INLINE_START    = 0x002f,
    UI_CSS_PROPERTY_JUSTIFY_CONTENT       = 0x0030,
    UI_CSS_PROPERTY_LEFT                  = 0x0031,
    UI_CSS_PROPERTY_LETTER_SPACING        = 0x0032,
    UI_CSS_PROPERTY_LINE_BREAK            = 0x0033,
    UI_CSS_PROPERTY_LINE_HEIGHT           = 0x0034,
    UI_CSS_PROPERTY_MARGIN                = 0x0035,
    UI_CSS_PROPERTY_MARGIN_BOTTOM         = 0x0036,
    UI_CSS_PROPERTY_MARGIN_LEFT           = 0x0037,
    UI_CSS_PROPERTY_MARGIN_RIGHT          = 0x0038,
    UI_CSS_PROPERTY_MARGIN_TOP            = 0x0039,
    UI_CSS_PROPERTY_MAX_HEIGHT            = 0x003a,
    UI_CSS_PROPERTY_MAX_WIDTH             = 0x003b,
    UI_CSS_PROPERTY_MIN_HEIGHT            = 0x003c,
    UI_CSS_PROPERTY_MIN_WIDTH             = 0x003d,
    UI_CSS_PROPERTY_OPACITY               = 0x003e,
    UI_CSS_PROPERTY_ORDER                 = 0x003f,
    UI_CSS_PROPERTY_OVERFLOW_BLOCK        = 0x0040,
    UI_CSS_PROPERTY_OVERFLOW_INLINE       = 0x0041,
    UI_CSS_PROPERTY_OVERFLOW_WRAP         = 0x0042,
    UI_CSS_PROPERTY_OVERFLOW_X            = 0x0043,
    UI_CSS_PROPERTY_OVERFLOW_Y            = 0x0044,
    UI_CSS_PROPERTY_PADDING               = 0x0045,
    UI_CSS_PROPERTY_PADDING_BOTTOM        = 0x0046,
    UI_CSS_PROPERTY_PADDING_LEFT          = 0x0047,
    UI_CSS_PROPERTY_PADDING_RIGHT         = 0x0048,
    UI_CSS_PROPERTY_PADDING_TOP           = 0x0049,
    UI_CSS_PROPERTY_POSITION              = 0x004a,
    UI_CSS_PROPERTY_RIGHT                 = 0x004b,
    UI_CSS_PROPERTY_TAB_SIZE              = 0x004c,
    UI_CSS_PROPERTY_TEXT_ALIGN            = 0x004d,
    UI_CSS_PROPERTY_TEXT_ALIGN_ALL        = 0x004e,
    UI_CSS_PROPERTY_TEXT_ALIGN_LAST       = 0x004f,
    UI_CSS_PROPERTY_TEXT_COMBINE_UPRIGHT  = 0x0050,
    UI_CSS_PROPERTY_TEXT_DECORATION       = 0x0051,
    UI_CSS_PROPERTY_TEXT_DECORATION_COLOR = 0x0052,
    UI_CSS_PROPERTY_TEXT_DECORATION_LINE  = 0x0053,
    UI_CSS_PROPERTY_TEXT_DECORATION_STYLE = 0x0054,
    UI_CSS_PROPERTY_TEXT_INDENT           = 0x0055,
    UI_CSS_PROPERTY_TEXT_JUSTIFY          = 0x0056,
    UI_CSS_PROPERTY_TEXT_ORIENTATION      = 0x0057,
    UI_CSS_PROPERTY_TEXT_OVERFLOW         = 0x0058,
    UI_CSS_PROPERTY_TEXT_TRANSFORM        = 0x0059,
    UI_CSS_PROPERTY_TOP                   = 0x005a,
    UI_CSS_PROPERTY_UNICODE_BIDI          = 0x005b,
    UI_CSS_PROPERTY_VERTICAL_ALIGN        = 0x005c,
    UI_CSS_PROPERTY_VISIBILITY            = 0x005d,
    UI_CSS_PROPERTY_WHITE_SPACE           = 0x005e,
    UI_CSS_PROPERTY_WIDTH                 = 0x005f,
    UI_CSS_PROPERTY_WORD_BREAK            = 0x0060,
    UI_CSS_PROPERTY_WORD_SPACING          = 0x0061,
    UI_CSS_PROPERTY_WORD_WRAP             = 0x0062,
    UI_CSS_PROPERTY_WRAP_FLOW             = 0x0063,
    UI_CSS_PROPERTY_WRAP_THROUGH          = 0x0064,
    UI_CSS_PROPERTY_WRITING_MODE          = 0x0065,
    UI_CSS_PROPERTY_Z_INDEX               = 0x0066,
    UI_CSS_VALUE_SPACE_EVENLY             = 0x0067,
    UI_CSS_PROPERTY__LAST_ENTRY           = 0x0068
};
typedef uintptr_t ui_css_property_type_t;

enum {
    UI_CSS_ALIGN_CONTENT_FLEX_START    = UI_CSS_VALUE_FLEX_START,
    UI_CSS_ALIGN_CONTENT_FLEX_END      = UI_CSS_VALUE_FLEX_END,
    UI_CSS_ALIGN_CONTENT_CENTER        = UI_CSS_VALUE_CENTER,
    UI_CSS_ALIGN_CONTENT_SPACE_BETWEEN = UI_CSS_VALUE_SPACE_BETWEEN,
    UI_CSS_ALIGN_CONTENT_SPACE_AROUND  = UI_CSS_VALUE_SPACE_AROUND,
    UI_CSS_ALIGN_CONTENT_STRETCH       = UI_CSS_VALUE_STRETCH
};
typedef unsigned int ui_css_align_content_type_t;

enum {
    UI_CSS_ALIGN_ITEMS_FLEX_START = UI_CSS_VALUE_FLEX_START,
    UI_CSS_ALIGN_ITEMS_FLEX_END   = UI_CSS_VALUE_FLEX_END,
    UI_CSS_ALIGN_ITEMS_CENTER     = UI_CSS_VALUE_CENTER,
    UI_CSS_ALIGN_ITEMS_BASELINE   = UI_CSS_VALUE_BASELINE,
    UI_CSS_ALIGN_ITEMS_STRETCH    = UI_CSS_VALUE_STRETCH
};
typedef unsigned int ui_css_align_items_type_t;

enum {
    UI_CSS_ALIGN_SELF_AUTO       = UI_CSS_VALUE_AUTO,
    UI_CSS_ALIGN_SELF_FLEX_START = UI_CSS_VALUE_FLEX_START,
    UI_CSS_ALIGN_SELF_FLEX_END   = UI_CSS_VALUE_FLEX_END,
    UI_CSS_ALIGN_SELF_CENTER     = UI_CSS_VALUE_CENTER,
    UI_CSS_ALIGN_SELF_BASELINE   = UI_CSS_VALUE_BASELINE,
    UI_CSS_ALIGN_SELF_STRETCH    = UI_CSS_VALUE_STRETCH
};
typedef unsigned int ui_css_align_self_type_t;

enum {
    UI_CSS_ALIGNMENT_BASELINE_BASELINE     = UI_CSS_VALUE_BASELINE,
    UI_CSS_ALIGNMENT_BASELINE_TEXT_BOTTOM  = UI_CSS_VALUE_TEXT_BOTTOM,
    UI_CSS_ALIGNMENT_BASELINE_ALPHABETIC   = UI_CSS_VALUE_ALPHABETIC,
    UI_CSS_ALIGNMENT_BASELINE_IDEOGRAPHIC  = UI_CSS_VALUE_IDEOGRAPHIC,
    UI_CSS_ALIGNMENT_BASELINE_MIDDLE       = UI_CSS_VALUE_MIDDLE,
    UI_CSS_ALIGNMENT_BASELINE_CENTRAL      = UI_CSS_VALUE_CENTRAL,
    UI_CSS_ALIGNMENT_BASELINE_MATHEMATICAL = UI_CSS_VALUE_MATHEMATICAL,
    UI_CSS_ALIGNMENT_BASELINE_TEXT_TOP     = UI_CSS_VALUE_TEXT_TOP
};
typedef unsigned int ui_css_alignment_baseline_type_t;



enum {
    UI_CSS_BASELINE_SHIFT__LENGTH     = UI_CSS_VALUE__LENGTH,
    UI_CSS_BASELINE_SHIFT__PERCENTAGE = UI_CSS_VALUE__PERCENTAGE,
    UI_CSS_BASELINE_SHIFT_SUB         = UI_CSS_VALUE_SUB,
    UI_CSS_BASELINE_SHIFT_SUPER       = UI_CSS_VALUE_SUPER,
    UI_CSS_BASELINE_SHIFT_TOP         = UI_CSS_VALUE_TOP,
    UI_CSS_BASELINE_SHIFT_CENTER      = UI_CSS_VALUE_CENTER,
    UI_CSS_BASELINE_SHIFT_BOTTOM      = UI_CSS_VALUE_BOTTOM
};
typedef unsigned int ui_css_baseline_shift_type_t;

enum {
    UI_CSS_BASELINE_SOURCE_AUTO  = UI_CSS_VALUE_AUTO,
    UI_CSS_BASELINE_SOURCE_FIRST = UI_CSS_VALUE_FIRST,
    UI_CSS_BASELINE_SOURCE_LAST  = UI_CSS_VALUE_LAST
};
typedef unsigned int ui_css_baseline_source_type_t;

enum {
    UI_CSS_BORDER_THIN    = UI_CSS_VALUE_THIN,
    UI_CSS_BORDER_MEDIUM  = UI_CSS_VALUE_MEDIUM,
    UI_CSS_BORDER_THICK   = UI_CSS_VALUE_THICK,
    UI_CSS_BORDER_NONE    = UI_CSS_VALUE_NONE,
    UI_CSS_BORDER_HIDDEN  = UI_CSS_VALUE_HIDDEN,
    UI_CSS_BORDER_DOTTED  = UI_CSS_VALUE_DOTTED,
    UI_CSS_BORDER_DASHED  = UI_CSS_VALUE_DASHED,
    UI_CSS_BORDER_SOLID   = UI_CSS_VALUE_SOLID,
    UI_CSS_BORDER_DOUBLE  = UI_CSS_VALUE_DOUBLE,
    UI_CSS_BORDER_GROOVE  = UI_CSS_VALUE_GROOVE,
    UI_CSS_BORDER_RIDGE   = UI_CSS_VALUE_RIDGE,
    UI_CSS_BORDER_INSET   = UI_CSS_VALUE_INSET,
    UI_CSS_BORDER_OUTSET  = UI_CSS_VALUE_OUTSET,
    UI_CSS_BORDER__LENGTH = UI_CSS_VALUE__LENGTH
};
typedef unsigned int ui_css_border_type_t;

enum {
    UI_CSS_BORDER_BOTTOM_THIN    = UI_CSS_VALUE_THIN,
    UI_CSS_BORDER_BOTTOM_MEDIUM  = UI_CSS_VALUE_MEDIUM,
    UI_CSS_BORDER_BOTTOM_THICK   = UI_CSS_VALUE_THICK,
    UI_CSS_BORDER_BOTTOM_NONE    = UI_CSS_VALUE_NONE,
    UI_CSS_BORDER_BOTTOM_HIDDEN  = UI_CSS_VALUE_HIDDEN,
    UI_CSS_BORDER_BOTTOM_DOTTED  = UI_CSS_VALUE_DOTTED,
    UI_CSS_BORDER_BOTTOM_DASHED  = UI_CSS_VALUE_DASHED,
    UI_CSS_BORDER_BOTTOM_SOLID   = UI_CSS_VALUE_SOLID,
    UI_CSS_BORDER_BOTTOM_DOUBLE  = UI_CSS_VALUE_DOUBLE,
    UI_CSS_BORDER_BOTTOM_GROOVE  = UI_CSS_VALUE_GROOVE,
    UI_CSS_BORDER_BOTTOM_RIDGE   = UI_CSS_VALUE_RIDGE,
    UI_CSS_BORDER_BOTTOM_INSET   = UI_CSS_VALUE_INSET,
    UI_CSS_BORDER_BOTTOM_OUTSET  = UI_CSS_VALUE_OUTSET,
    UI_CSS_BORDER_BOTTOM__LENGTH = UI_CSS_VALUE__LENGTH
};
typedef unsigned int ui_css_border_bottom_type_t;



enum {
    UI_CSS_BORDER_LEFT_THIN    = UI_CSS_VALUE_THIN,
    UI_CSS_BORDER_LEFT_MEDIUM  = UI_CSS_VALUE_MEDIUM,
    UI_CSS_BORDER_LEFT_THICK   = UI_CSS_VALUE_THICK,
    UI_CSS_BORDER_LEFT_NONE    = UI_CSS_VALUE_NONE,
    UI_CSS_BORDER_LEFT_HIDDEN  = UI_CSS_VALUE_HIDDEN,
    UI_CSS_BORDER_LEFT_DOTTED  = UI_CSS_VALUE_DOTTED,
    UI_CSS_BORDER_LEFT_DASHED  = UI_CSS_VALUE_DASHED,
    UI_CSS_BORDER_LEFT_SOLID   = UI_CSS_VALUE_SOLID,
    UI_CSS_BORDER_LEFT_DOUBLE  = UI_CSS_VALUE_DOUBLE,
    UI_CSS_BORDER_LEFT_GROOVE  = UI_CSS_VALUE_GROOVE,
    UI_CSS_BORDER_LEFT_RIDGE   = UI_CSS_VALUE_RIDGE,
    UI_CSS_BORDER_LEFT_INSET   = UI_CSS_VALUE_INSET,
    UI_CSS_BORDER_LEFT_OUTSET  = UI_CSS_VALUE_OUTSET,
    UI_CSS_BORDER_LEFT__LENGTH = UI_CSS_VALUE__LENGTH
};
typedef unsigned int ui_css_border_left_type_t;



enum {
    UI_CSS_BORDER_RIGHT_THIN    = UI_CSS_VALUE_THIN,
    UI_CSS_BORDER_RIGHT_MEDIUM  = UI_CSS_VALUE_MEDIUM,
    UI_CSS_BORDER_RIGHT_THICK   = UI_CSS_VALUE_THICK,
    UI_CSS_BORDER_RIGHT_NONE    = UI_CSS_VALUE_NONE,
    UI_CSS_BORDER_RIGHT_HIDDEN  = UI_CSS_VALUE_HIDDEN,
    UI_CSS_BORDER_RIGHT_DOTTED  = UI_CSS_VALUE_DOTTED,
    UI_CSS_BORDER_RIGHT_DASHED  = UI_CSS_VALUE_DASHED,
    UI_CSS_BORDER_RIGHT_SOLID   = UI_CSS_VALUE_SOLID,
    UI_CSS_BORDER_RIGHT_DOUBLE  = UI_CSS_VALUE_DOUBLE,
    UI_CSS_BORDER_RIGHT_GROOVE  = UI_CSS_VALUE_GROOVE,
    UI_CSS_BORDER_RIGHT_RIDGE   = UI_CSS_VALUE_RIDGE,
    UI_CSS_BORDER_RIGHT_INSET   = UI_CSS_VALUE_INSET,
    UI_CSS_BORDER_RIGHT_OUTSET  = UI_CSS_VALUE_OUTSET,
    UI_CSS_BORDER_RIGHT__LENGTH = UI_CSS_VALUE__LENGTH
};
typedef unsigned int ui_css_border_right_type_t;



enum {
    UI_CSS_BORDER_TOP_THIN    = UI_CSS_VALUE_THIN,
    UI_CSS_BORDER_TOP_MEDIUM  = UI_CSS_VALUE_MEDIUM,
    UI_CSS_BORDER_TOP_THICK   = UI_CSS_VALUE_THICK,
    UI_CSS_BORDER_TOP_NONE    = UI_CSS_VALUE_NONE,
    UI_CSS_BORDER_TOP_HIDDEN  = UI_CSS_VALUE_HIDDEN,
    UI_CSS_BORDER_TOP_DOTTED  = UI_CSS_VALUE_DOTTED,
    UI_CSS_BORDER_TOP_DASHED  = UI_CSS_VALUE_DASHED,
    UI_CSS_BORDER_TOP_SOLID   = UI_CSS_VALUE_SOLID,
    UI_CSS_BORDER_TOP_DOUBLE  = UI_CSS_VALUE_DOUBLE,
    UI_CSS_BORDER_TOP_GROOVE  = UI_CSS_VALUE_GROOVE,
    UI_CSS_BORDER_TOP_RIDGE   = UI_CSS_VALUE_RIDGE,
    UI_CSS_BORDER_TOP_INSET   = UI_CSS_VALUE_INSET,
    UI_CSS_BORDER_TOP_OUTSET  = UI_CSS_VALUE_OUTSET,
    UI_CSS_BORDER_TOP__LENGTH = UI_CSS_VALUE__LENGTH
};
typedef unsigned int ui_css_border_top_type_t;



enum {
    UI_CSS_BOTTOM_AUTO        = UI_CSS_VALUE_AUTO,
    UI_CSS_BOTTOM__LENGTH     = UI_CSS_VALUE__LENGTH,
    UI_CSS_BOTTOM__PERCENTAGE = UI_CSS_VALUE__PERCENTAGE
};
typedef unsigned int ui_css_bottom_type_t;

enum {
    UI_CSS_BOX_SIZING_CONTENT_BOX = UI_CSS_VALUE_CONTENT_BOX,
    UI_CSS_BOX_SIZING_BORDER_BOX  = UI_CSS_VALUE_BORDER_BOX
};
typedef unsigned int ui_css_box_sizing_type_t;

enum {
    UI_CSS_CLEAR_INLINE_START = UI_CSS_VALUE_INLINE_START,
    UI_CSS_CLEAR_INLINE_END   = UI_CSS_VALUE_INLINE_END,
    UI_CSS_CLEAR_BLOCK_START  = UI_CSS_VALUE_BLOCK_START,
    UI_CSS_CLEAR_BLOCK_END    = UI_CSS_VALUE_BLOCK_END,
    UI_CSS_CLEAR_LEFT         = UI_CSS_VALUE_LEFT,
    UI_CSS_CLEAR_RIGHT        = UI_CSS_VALUE_RIGHT,
    UI_CSS_CLEAR_TOP          = UI_CSS_VALUE_TOP,
    UI_CSS_CLEAR_BOTTOM       = UI_CSS_VALUE_BOTTOM,
    UI_CSS_CLEAR_NONE         = UI_CSS_VALUE_NONE
};
typedef unsigned int ui_css_clear_type_t;

enum {
    UI_CSS_COLOR_CURRENTCOLOR         = UI_CSS_VALUE_CURRENTCOLOR,
    UI_CSS_COLOR_TRANSPARENT          = UI_CSS_VALUE_TRANSPARENT,
    UI_CSS_COLOR_HEX                  = UI_CSS_VALUE_HEX,
    UI_CSS_COLOR_ALICEBLUE            = UI_CSS_VALUE_ALICEBLUE,
    UI_CSS_COLOR_ANTIQUEWHITE         = UI_CSS_VALUE_ANTIQUEWHITE,
    UI_CSS_COLOR_AQUA                 = UI_CSS_VALUE_AQUA,
    UI_CSS_COLOR_AQUAMARINE           = UI_CSS_VALUE_AQUAMARINE,
    UI_CSS_COLOR_AZURE                = UI_CSS_VALUE_AZURE,
    UI_CSS_COLOR_BEIGE                = UI_CSS_VALUE_BEIGE,
    UI_CSS_COLOR_BISQUE               = UI_CSS_VALUE_BISQUE,
    UI_CSS_COLOR_BLACK                = UI_CSS_VALUE_BLACK,
    UI_CSS_COLOR_BLANCHEDALMOND       = UI_CSS_VALUE_BLANCHEDALMOND,
    UI_CSS_COLOR_BLUE                 = UI_CSS_VALUE_BLUE,
    UI_CSS_COLOR_BLUEVIOLET           = UI_CSS_VALUE_BLUEVIOLET,
    UI_CSS_COLOR_BROWN                = UI_CSS_VALUE_BROWN,
    UI_CSS_COLOR_BURLYWOOD            = UI_CSS_VALUE_BURLYWOOD,
    UI_CSS_COLOR_CADETBLUE            = UI_CSS_VALUE_CADETBLUE,
    UI_CSS_COLOR_CHARTREUSE           = UI_CSS_VALUE_CHARTREUSE,
    UI_CSS_COLOR_CHOCOLATE            = UI_CSS_VALUE_CHOCOLATE,
    UI_CSS_COLOR_CORAL                = UI_CSS_VALUE_CORAL,
    UI_CSS_COLOR_CORNFLOWERBLUE       = UI_CSS_VALUE_CORNFLOWERBLUE,
    UI_CSS_COLOR_CORNSILK             = UI_CSS_VALUE_CORNSILK,
    UI_CSS_COLOR_CRIMSON              = UI_CSS_VALUE_CRIMSON,
    UI_CSS_COLOR_CYAN                 = UI_CSS_VALUE_CYAN,
    UI_CSS_COLOR_DARKBLUE             = UI_CSS_VALUE_DARKBLUE,
    UI_CSS_COLOR_DARKCYAN             = UI_CSS_VALUE_DARKCYAN,
    UI_CSS_COLOR_DARKGOLDENROD        = UI_CSS_VALUE_DARKGOLDENROD,
    UI_CSS_COLOR_DARKGRAY             = UI_CSS_VALUE_DARKGRAY,
    UI_CSS_COLOR_DARKGREEN            = UI_CSS_VALUE_DARKGREEN,
    UI_CSS_COLOR_DARKGREY             = UI_CSS_VALUE_DARKGREY,
    UI_CSS_COLOR_DARKKHAKI            = UI_CSS_VALUE_DARKKHAKI,
    UI_CSS_COLOR_DARKMAGENTA          = UI_CSS_VALUE_DARKMAGENTA,
    UI_CSS_COLOR_DARKOLIVEGREEN       = UI_CSS_VALUE_DARKOLIVEGREEN,
    UI_CSS_COLOR_DARKORANGE           = UI_CSS_VALUE_DARKORANGE,
    UI_CSS_COLOR_DARKORCHID           = UI_CSS_VALUE_DARKORCHID,
    UI_CSS_COLOR_DARKRED              = UI_CSS_VALUE_DARKRED,
    UI_CSS_COLOR_DARKSALMON           = UI_CSS_VALUE_DARKSALMON,
    UI_CSS_COLOR_DARKSEAGREEN         = UI_CSS_VALUE_DARKSEAGREEN,
    UI_CSS_COLOR_DARKSLATEBLUE        = UI_CSS_VALUE_DARKSLATEBLUE,
    UI_CSS_COLOR_DARKSLATEGRAY        = UI_CSS_VALUE_DARKSLATEGRAY,
    UI_CSS_COLOR_DARKSLATEGREY        = UI_CSS_VALUE_DARKSLATEGREY,
    UI_CSS_COLOR_DARKTURQUOISE        = UI_CSS_VALUE_DARKTURQUOISE,
    UI_CSS_COLOR_DARKVIOLET           = UI_CSS_VALUE_DARKVIOLET,
    UI_CSS_COLOR_DEEPPINK             = UI_CSS_VALUE_DEEPPINK,
    UI_CSS_COLOR_DEEPSKYBLUE          = UI_CSS_VALUE_DEEPSKYBLUE,
    UI_CSS_COLOR_DIMGRAY              = UI_CSS_VALUE_DIMGRAY,
    UI_CSS_COLOR_DIMGREY              = UI_CSS_VALUE_DIMGREY,
    UI_CSS_COLOR_DODGERBLUE           = UI_CSS_VALUE_DODGERBLUE,
    UI_CSS_COLOR_FIREBRICK            = UI_CSS_VALUE_FIREBRICK,
    UI_CSS_COLOR_FLORALWHITE          = UI_CSS_VALUE_FLORALWHITE,
    UI_CSS_COLOR_FORESTGREEN          = UI_CSS_VALUE_FORESTGREEN,
    UI_CSS_COLOR_FUCHSIA              = UI_CSS_VALUE_FUCHSIA,
    UI_CSS_COLOR_GAINSBORO            = UI_CSS_VALUE_GAINSBORO,
    UI_CSS_COLOR_GHOSTWHITE           = UI_CSS_VALUE_GHOSTWHITE,
    UI_CSS_COLOR_GOLD                 = UI_CSS_VALUE_GOLD,
    UI_CSS_COLOR_GOLDENROD            = UI_CSS_VALUE_GOLDENROD,
    UI_CSS_COLOR_GRAY                 = UI_CSS_VALUE_GRAY,
    UI_CSS_COLOR_GREEN                = UI_CSS_VALUE_GREEN,
    UI_CSS_COLOR_GREENYELLOW          = UI_CSS_VALUE_GREENYELLOW,
    UI_CSS_COLOR_GREY                 = UI_CSS_VALUE_GREY,
    UI_CSS_COLOR_HONEYDEW             = UI_CSS_VALUE_HONEYDEW,
    UI_CSS_COLOR_HOTPINK              = UI_CSS_VALUE_HOTPINK,
    UI_CSS_COLOR_INDIANRED            = UI_CSS_VALUE_INDIANRED,
    UI_CSS_COLOR_INDIGO               = UI_CSS_VALUE_INDIGO,
    UI_CSS_COLOR_IVORY                = UI_CSS_VALUE_IVORY,
    UI_CSS_COLOR_KHAKI                = UI_CSS_VALUE_KHAKI,
    UI_CSS_COLOR_LAVENDER             = UI_CSS_VALUE_LAVENDER,
    UI_CSS_COLOR_LAVENDERBLUSH        = UI_CSS_VALUE_LAVENDERBLUSH,
    UI_CSS_COLOR_LAWNGREEN            = UI_CSS_VALUE_LAWNGREEN,
    UI_CSS_COLOR_LEMONCHIFFON         = UI_CSS_VALUE_LEMONCHIFFON,
    UI_CSS_COLOR_LIGHTBLUE            = UI_CSS_VALUE_LIGHTBLUE,
    UI_CSS_COLOR_LIGHTCORAL           = UI_CSS_VALUE_LIGHTCORAL,
    UI_CSS_COLOR_LIGHTCYAN            = UI_CSS_VALUE_LIGHTCYAN,
    UI_CSS_COLOR_LIGHTGOLDENRODYELLOW = UI_CSS_VALUE_LIGHTGOLDENRODYELLOW,
    UI_CSS_COLOR_LIGHTGRAY            = UI_CSS_VALUE_LIGHTGRAY,
    UI_CSS_COLOR_LIGHTGREEN           = UI_CSS_VALUE_LIGHTGREEN,
    UI_CSS_COLOR_LIGHTGREY            = UI_CSS_VALUE_LIGHTGREY,
    UI_CSS_COLOR_LIGHTPINK            = UI_CSS_VALUE_LIGHTPINK,
    UI_CSS_COLOR_LIGHTSALMON          = UI_CSS_VALUE_LIGHTSALMON,
    UI_CSS_COLOR_LIGHTSEAGREEN        = UI_CSS_VALUE_LIGHTSEAGREEN,
    UI_CSS_COLOR_LIGHTSKYBLUE         = UI_CSS_VALUE_LIGHTSKYBLUE,
    UI_CSS_COLOR_LIGHTSLATEGRAY       = UI_CSS_VALUE_LIGHTSLATEGRAY,
    UI_CSS_COLOR_LIGHTSLATEGREY       = UI_CSS_VALUE_LIGHTSLATEGREY,
    UI_CSS_COLOR_LIGHTSTEELBLUE       = UI_CSS_VALUE_LIGHTSTEELBLUE,
    UI_CSS_COLOR_LIGHTYELLOW          = UI_CSS_VALUE_LIGHTYELLOW,
    UI_CSS_COLOR_LIME                 = UI_CSS_VALUE_LIME,
    UI_CSS_COLOR_LIMEGREEN            = UI_CSS_VALUE_LIMEGREEN,
    UI_CSS_COLOR_LINEN                = UI_CSS_VALUE_LINEN,
    UI_CSS_COLOR_MAGENTA              = UI_CSS_VALUE_MAGENTA,
    UI_CSS_COLOR_MAROON               = UI_CSS_VALUE_MAROON,
    UI_CSS_COLOR_MEDIUMAQUAMARINE     = UI_CSS_VALUE_MEDIUMAQUAMARINE,
    UI_CSS_COLOR_MEDIUMBLUE           = UI_CSS_VALUE_MEDIUMBLUE,
    UI_CSS_COLOR_MEDIUMORCHID         = UI_CSS_VALUE_MEDIUMORCHID,
    UI_CSS_COLOR_MEDIUMPURPLE         = UI_CSS_VALUE_MEDIUMPURPLE,
    UI_CSS_COLOR_MEDIUMSEAGREEN       = UI_CSS_VALUE_MEDIUMSEAGREEN,
    UI_CSS_COLOR_MEDIUMSLATEBLUE      = UI_CSS_VALUE_MEDIUMSLATEBLUE,
    UI_CSS_COLOR_MEDIUMSPRINGGREEN    = UI_CSS_VALUE_MEDIUMSPRINGGREEN,
    UI_CSS_COLOR_MEDIUMTURQUOISE      = UI_CSS_VALUE_MEDIUMTURQUOISE,
    UI_CSS_COLOR_MEDIUMVIOLETRED      = UI_CSS_VALUE_MEDIUMVIOLETRED,
    UI_CSS_COLOR_MIDNIGHTBLUE         = UI_CSS_VALUE_MIDNIGHTBLUE,
    UI_CSS_COLOR_MINTCREAM            = UI_CSS_VALUE_MINTCREAM,
    UI_CSS_COLOR_MISTYROSE            = UI_CSS_VALUE_MISTYROSE,
    UI_CSS_COLOR_MOCCASIN             = UI_CSS_VALUE_MOCCASIN,
    UI_CSS_COLOR_NAVAJOWHITE          = UI_CSS_VALUE_NAVAJOWHITE,
    UI_CSS_COLOR_NAVY                 = UI_CSS_VALUE_NAVY,
    UI_CSS_COLOR_OLDLACE              = UI_CSS_VALUE_OLDLACE,
    UI_CSS_COLOR_OLIVE                = UI_CSS_VALUE_OLIVE,
    UI_CSS_COLOR_OLIVEDRAB            = UI_CSS_VALUE_OLIVEDRAB,
    UI_CSS_COLOR_ORANGE               = UI_CSS_VALUE_ORANGE,
    UI_CSS_COLOR_ORANGERED            = UI_CSS_VALUE_ORANGERED,
    UI_CSS_COLOR_ORCHID               = UI_CSS_VALUE_ORCHID,
    UI_CSS_COLOR_PALEGOLDENROD        = UI_CSS_VALUE_PALEGOLDENROD,
    UI_CSS_COLOR_PALEGREEN            = UI_CSS_VALUE_PALEGREEN,
    UI_CSS_COLOR_PALETURQUOISE        = UI_CSS_VALUE_PALETURQUOISE,
    UI_CSS_COLOR_PALEVIOLETRED        = UI_CSS_VALUE_PALEVIOLETRED,
    UI_CSS_COLOR_PAPAYAWHIP           = UI_CSS_VALUE_PAPAYAWHIP,
    UI_CSS_COLOR_PEACHPUFF            = UI_CSS_VALUE_PEACHPUFF,
    UI_CSS_COLOR_PERU                 = UI_CSS_VALUE_PERU,
    UI_CSS_COLOR_PINK                 = UI_CSS_VALUE_PINK,
    UI_CSS_COLOR_PLUM                 = UI_CSS_VALUE_PLUM,
    UI_CSS_COLOR_POWDERBLUE           = UI_CSS_VALUE_POWDERBLUE,
    UI_CSS_COLOR_PURPLE               = UI_CSS_VALUE_PURPLE,
    UI_CSS_COLOR_REBECCAPURPLE        = UI_CSS_VALUE_REBECCAPURPLE,
    UI_CSS_COLOR_RED                  = UI_CSS_VALUE_RED,
    UI_CSS_COLOR_ROSYBROWN            = UI_CSS_VALUE_ROSYBROWN,
    UI_CSS_COLOR_ROYALBLUE            = UI_CSS_VALUE_ROYALBLUE,
    UI_CSS_COLOR_SADDLEBROWN          = UI_CSS_VALUE_SADDLEBROWN,
    UI_CSS_COLOR_SALMON               = UI_CSS_VALUE_SALMON,
    UI_CSS_COLOR_SANDYBROWN           = UI_CSS_VALUE_SANDYBROWN,
    UI_CSS_COLOR_SEAGREEN             = UI_CSS_VALUE_SEAGREEN,
    UI_CSS_COLOR_SEASHELL             = UI_CSS_VALUE_SEASHELL,
    UI_CSS_COLOR_SIENNA               = UI_CSS_VALUE_SIENNA,
    UI_CSS_COLOR_SILVER               = UI_CSS_VALUE_SILVER,
    UI_CSS_COLOR_SKYBLUE              = UI_CSS_VALUE_SKYBLUE,
    UI_CSS_COLOR_SLATEBLUE            = UI_CSS_VALUE_SLATEBLUE,
    UI_CSS_COLOR_SLATEGRAY            = UI_CSS_VALUE_SLATEGRAY,
    UI_CSS_COLOR_SLATEGREY            = UI_CSS_VALUE_SLATEGREY,
    UI_CSS_COLOR_SNOW                 = UI_CSS_VALUE_SNOW,
    UI_CSS_COLOR_SPRINGGREEN          = UI_CSS_VALUE_SPRINGGREEN,
    UI_CSS_COLOR_STEELBLUE            = UI_CSS_VALUE_STEELBLUE,
    UI_CSS_COLOR_TAN                  = UI_CSS_VALUE_TAN,
    UI_CSS_COLOR_TEAL                 = UI_CSS_VALUE_TEAL,
    UI_CSS_COLOR_THISTLE              = UI_CSS_VALUE_THISTLE,
    UI_CSS_COLOR_TOMATO               = UI_CSS_VALUE_TOMATO,
    UI_CSS_COLOR_TURQUOISE            = UI_CSS_VALUE_TURQUOISE,
    UI_CSS_COLOR_VIOLET               = UI_CSS_VALUE_VIOLET,
    UI_CSS_COLOR_WHEAT                = UI_CSS_VALUE_WHEAT,
    UI_CSS_COLOR_WHITE                = UI_CSS_VALUE_WHITE,
    UI_CSS_COLOR_WHITESMOKE           = UI_CSS_VALUE_WHITESMOKE,
    UI_CSS_COLOR_YELLOW               = UI_CSS_VALUE_YELLOW,
    UI_CSS_COLOR_YELLOWGREEN          = UI_CSS_VALUE_YELLOWGREEN,
    UI_CSS_COLOR_CANVAS               = UI_CSS_VALUE_CANVAS,
    UI_CSS_COLOR_CANVASTEXT           = UI_CSS_VALUE_CANVASTEXT,
    UI_CSS_COLOR_LINKTEXT             = UI_CSS_VALUE_LINKTEXT,
    UI_CSS_COLOR_VISITEDTEXT          = UI_CSS_VALUE_VISITEDTEXT,
    UI_CSS_COLOR_ACTIVETEXT           = UI_CSS_VALUE_ACTIVETEXT,
    UI_CSS_COLOR_BUTTONFACE           = UI_CSS_VALUE_BUTTONFACE,
    UI_CSS_COLOR_BUTTONTEXT           = UI_CSS_VALUE_BUTTONTEXT,
    UI_CSS_COLOR_BUTTONBORDER         = UI_CSS_VALUE_BUTTONBORDER,
    UI_CSS_COLOR_FIELD                = UI_CSS_VALUE_FIELD,
    UI_CSS_COLOR_FIELDTEXT            = UI_CSS_VALUE_FIELDTEXT,
    UI_CSS_COLOR_HIGHLIGHT            = UI_CSS_VALUE_HIGHLIGHT,
    UI_CSS_COLOR_HIGHLIGHTTEXT        = UI_CSS_VALUE_HIGHLIGHTTEXT,
    UI_CSS_COLOR_SELECTEDITEM         = UI_CSS_VALUE_SELECTEDITEM,
    UI_CSS_COLOR_SELECTEDITEMTEXT     = UI_CSS_VALUE_SELECTEDITEMTEXT,
    UI_CSS_COLOR_MARK                 = UI_CSS_VALUE_MARK,
    UI_CSS_COLOR_MARKTEXT             = UI_CSS_VALUE_MARKTEXT,
    UI_CSS_COLOR_GRAYTEXT             = UI_CSS_VALUE_GRAYTEXT,
    UI_CSS_COLOR_ACCENTCOLOR          = UI_CSS_VALUE_ACCENTCOLOR,
    UI_CSS_COLOR_ACCENTCOLORTEXT      = UI_CSS_VALUE_ACCENTCOLORTEXT,
    UI_CSS_COLOR_RGB                  = UI_CSS_VALUE_RGB,
    UI_CSS_COLOR_RGBA                 = UI_CSS_VALUE_RGBA,
    UI_CSS_COLOR_HSL                  = UI_CSS_VALUE_HSL,
    UI_CSS_COLOR_HSLA                 = UI_CSS_VALUE_HSLA,
    UI_CSS_COLOR_HWB                  = UI_CSS_VALUE_HWB,
    UI_CSS_COLOR_LAB                  = UI_CSS_VALUE_LAB,
    UI_CSS_COLOR_LCH                  = UI_CSS_VALUE_LCH,
    UI_CSS_COLOR_OKLAB                = UI_CSS_VALUE_OKLAB,
    UI_CSS_COLOR_OKLCH                = UI_CSS_VALUE_OKLCH,
    UI_CSS_COLOR_COLOR                = UI_CSS_VALUE_COLOR
};
typedef unsigned int ui_css_color_type_t;

enum {
    UI_CSS_DIRECTION_LTR = UI_CSS_VALUE_LTR,
    UI_CSS_DIRECTION_RTL = UI_CSS_VALUE_RTL
};
typedef unsigned int ui_css_direction_type_t;

enum {
    UI_CSS_DISPLAY_BLOCK               = UI_CSS_VALUE_BLOCK,
    UI_CSS_DISPLAY_INLINE              = UI_CSS_VALUE_INLINE,
    UI_CSS_DISPLAY_RUN_IN              = UI_CSS_VALUE_RUN_IN,
    UI_CSS_DISPLAY_FLOW                = UI_CSS_VALUE_FLOW,
    UI_CSS_DISPLAY_FLOW_ROOT           = UI_CSS_VALUE_FLOW_ROOT,
    UI_CSS_DISPLAY_TABLE               = UI_CSS_VALUE_TABLE,
    UI_CSS_DISPLAY_FLEX                = UI_CSS_VALUE_FLEX,
    UI_CSS_DISPLAY_GRID                = UI_CSS_VALUE_GRID,
    UI_CSS_DISPLAY_RUBY                = UI_CSS_VALUE_RUBY,
    UI_CSS_DISPLAY_LIST_ITEM           = UI_CSS_VALUE_LIST_ITEM,
    UI_CSS_DISPLAY_TABLE_ROW_GROUP     = UI_CSS_VALUE_TABLE_ROW_GROUP,
    UI_CSS_DISPLAY_TABLE_HEADER_GROUP  = UI_CSS_VALUE_TABLE_HEADER_GROUP,
    UI_CSS_DISPLAY_TABLE_FOOTER_GROUP  = UI_CSS_VALUE_TABLE_FOOTER_GROUP,
    UI_CSS_DISPLAY_TABLE_ROW           = UI_CSS_VALUE_TABLE_ROW,
    UI_CSS_DISPLAY_TABLE_CELL          = UI_CSS_VALUE_TABLE_CELL,
    UI_CSS_DISPLAY_TABLE_COLUMN_GROUP  = UI_CSS_VALUE_TABLE_COLUMN_GROUP,
    UI_CSS_DISPLAY_TABLE_COLUMN        = UI_CSS_VALUE_TABLE_COLUMN,
    UI_CSS_DISPLAY_TABLE_CAPTION       = UI_CSS_VALUE_TABLE_CAPTION,
    UI_CSS_DISPLAY_RUBY_BASE           = UI_CSS_VALUE_RUBY_BASE,
    UI_CSS_DISPLAY_RUBY_TEXT           = UI_CSS_VALUE_RUBY_TEXT,
    UI_CSS_DISPLAY_RUBY_BASE_CONTAINER = UI_CSS_VALUE_RUBY_BASE_CONTAINER,
    UI_CSS_DISPLAY_RUBY_TEXT_CONTAINER = UI_CSS_VALUE_RUBY_TEXT_CONTAINER,
    UI_CSS_DISPLAY_CONTENTS            = UI_CSS_VALUE_CONTENTS,
    UI_CSS_DISPLAY_NONE                = UI_CSS_VALUE_NONE,
    UI_CSS_DISPLAY_INLINE_BLOCK        = UI_CSS_VALUE_INLINE_BLOCK,
    UI_CSS_DISPLAY_INLINE_TABLE        = UI_CSS_VALUE_INLINE_TABLE,
    UI_CSS_DISPLAY_INLINE_FLEX         = UI_CSS_VALUE_INLINE_FLEX,
    UI_CSS_DISPLAY_INLINE_GRID         = UI_CSS_VALUE_INLINE_GRID
};
typedef unsigned int ui_css_display_type_t;

enum {
    UI_CSS_DOMINANT_BASELINE_AUTO         = UI_CSS_VALUE_AUTO,
    UI_CSS_DOMINANT_BASELINE_TEXT_BOTTOM  = UI_CSS_VALUE_TEXT_BOTTOM,
    UI_CSS_DOMINANT_BASELINE_ALPHABETIC   = UI_CSS_VALUE_ALPHABETIC,
    UI_CSS_DOMINANT_BASELINE_IDEOGRAPHIC  = UI_CSS_VALUE_IDEOGRAPHIC,
    UI_CSS_DOMINANT_BASELINE_MIDDLE       = UI_CSS_VALUE_MIDDLE,
    UI_CSS_DOMINANT_BASELINE_CENTRAL      = UI_CSS_VALUE_CENTRAL,
    UI_CSS_DOMINANT_BASELINE_MATHEMATICAL = UI_CSS_VALUE_MATHEMATICAL,
    UI_CSS_DOMINANT_BASELINE_HANGING      = UI_CSS_VALUE_HANGING,
    UI_CSS_DOMINANT_BASELINE_TEXT_TOP     = UI_CSS_VALUE_TEXT_TOP
};
typedef unsigned int ui_css_dominant_baseline_type_t;

enum {
    UI_CSS_FLEX_NONE = UI_CSS_VALUE_NONE
};
typedef unsigned int ui_css_flex_type_t;

enum {
    UI_CSS_FLEX_BASIS_CONTENT = UI_CSS_VALUE_CONTENT,
    UI_CSS_FLEX_BASIS__LENGTH     = UI_CSS_VALUE__LENGTH,
    UI_CSS_FLEX_BASIS__PERCENTAGE = UI_CSS_VALUE__PERCENTAGE
};
typedef unsigned int ui_css_flex_basis_type_t;

enum {
    UI_CSS_FLEX_DIRECTION_ROW            = UI_CSS_VALUE_ROW,
    UI_CSS_FLEX_DIRECTION_ROW_REVERSE    = UI_CSS_VALUE_ROW_REVERSE,
    UI_CSS_FLEX_DIRECTION_COLUMN         = UI_CSS_VALUE_COLUMN,
    UI_CSS_FLEX_DIRECTION_COLUMN_REVERSE = UI_CSS_VALUE_COLUMN_REVERSE
};
typedef unsigned int ui_css_flex_direction_type_t;



enum {
    UI_CSS_FLEX_GROW__NUMBER = UI_CSS_VALUE__NUMBER
};
typedef unsigned int ui_css_flex_grow_type_t;

enum {
    UI_CSS_FLEX_SHRINK__NUMBER = UI_CSS_VALUE__NUMBER
};
typedef unsigned int ui_css_flex_shrink_type_t;

enum {
    UI_CSS_FLEX_WRAP_NOWRAP       = UI_CSS_VALUE_NOWRAP,
    UI_CSS_FLEX_WRAP_WRAP         = UI_CSS_VALUE_WRAP,
    UI_CSS_FLEX_WRAP_WRAP_REVERSE = UI_CSS_VALUE_WRAP_REVERSE
};
typedef unsigned int ui_css_flex_wrap_type_t;

enum {
    UI_CSS_FLOAT_BLOCK_START  = UI_CSS_VALUE_BLOCK_START,
    UI_CSS_FLOAT_BLOCK_END    = UI_CSS_VALUE_BLOCK_END,
    UI_CSS_FLOAT_INLINE_START = UI_CSS_VALUE_INLINE_START,
    UI_CSS_FLOAT_INLINE_END   = UI_CSS_VALUE_INLINE_END,
    UI_CSS_FLOAT_SNAP_BLOCK   = UI_CSS_VALUE_SNAP_BLOCK,
    UI_CSS_FLOAT_START        = UI_CSS_VALUE_START,
    UI_CSS_FLOAT_END          = UI_CSS_VALUE_END,
    UI_CSS_FLOAT_NEAR         = UI_CSS_VALUE_NEAR,
    UI_CSS_FLOAT_SNAP_INLINE  = UI_CSS_VALUE_SNAP_INLINE,
    UI_CSS_FLOAT_LEFT         = UI_CSS_VALUE_LEFT,
    UI_CSS_FLOAT_RIGHT        = UI_CSS_VALUE_RIGHT,
    UI_CSS_FLOAT_TOP          = UI_CSS_VALUE_TOP,
    UI_CSS_FLOAT_BOTTOM       = UI_CSS_VALUE_BOTTOM,
    UI_CSS_FLOAT_NONE         = UI_CSS_VALUE_NONE
};
typedef unsigned int ui_css_float_type_t;

enum {
    UI_CSS_FLOAT_DEFER__INTEGER = UI_CSS_VALUE__INTEGER,
    UI_CSS_FLOAT_DEFER_LAST     = UI_CSS_VALUE_LAST,
    UI_CSS_FLOAT_DEFER_NONE     = UI_CSS_VALUE_NONE
};
typedef unsigned int ui_css_float_defer_type_t;

enum {
    UI_CSS_FLOAT_OFFSET__LENGTH     = UI_CSS_VALUE__LENGTH,
    UI_CSS_FLOAT_OFFSET__PERCENTAGE = UI_CSS_VALUE__PERCENTAGE
};
typedef unsigned int ui_css_float_offset_type_t;

enum {
    UI_CSS_FLOAT_REFERENCE_INLINE = UI_CSS_VALUE_INLINE,
    UI_CSS_FLOAT_REFERENCE_COLUMN = UI_CSS_VALUE_COLUMN,
    UI_CSS_FLOAT_REFERENCE_REGION = UI_CSS_VALUE_REGION,
    UI_CSS_FLOAT_REFERENCE_PAGE   = UI_CSS_VALUE_PAGE
};
typedef unsigned int ui_css_float_reference_type_t;

enum {
    UI_CSS_FONT_FAMILY_SERIF         = UI_CSS_VALUE_SERIF,
    UI_CSS_FONT_FAMILY_SANS_SERIF    = UI_CSS_VALUE_SANS_SERIF,
    UI_CSS_FONT_FAMILY_CURSIVE       = UI_CSS_VALUE_CURSIVE,
    UI_CSS_FONT_FAMILY_FANTASY       = UI_CSS_VALUE_FANTASY,
    UI_CSS_FONT_FAMILY_MONOSPACE     = UI_CSS_VALUE_MONOSPACE,
    UI_CSS_FONT_FAMILY_SYSTEM_UI     = UI_CSS_VALUE_SYSTEM_UI,
    UI_CSS_FONT_FAMILY_EMOJI         = UI_CSS_VALUE_EMOJI,
    UI_CSS_FONT_FAMILY_MATH          = UI_CSS_VALUE_MATH,
    UI_CSS_FONT_FAMILY_FANGSONG      = UI_CSS_VALUE_FANGSONG,
    UI_CSS_FONT_FAMILY_UI_SERIF      = UI_CSS_VALUE_UI_SERIF,
    UI_CSS_FONT_FAMILY_UI_SANS_SERIF = UI_CSS_VALUE_UI_SANS_SERIF,
    UI_CSS_FONT_FAMILY_UI_MONOSPACE  = UI_CSS_VALUE_UI_MONOSPACE,
    UI_CSS_FONT_FAMILY_UI_ROUNDED    = UI_CSS_VALUE_UI_ROUNDED
};
typedef unsigned int ui_css_font_family_type_t;

enum {
    UI_CSS_FONT_SIZE_XX_SMALL  = UI_CSS_VALUE_XX_SMALL,
    UI_CSS_FONT_SIZE_X_SMALL   = UI_CSS_VALUE_X_SMALL,
    UI_CSS_FONT_SIZE_SMALL     = UI_CSS_VALUE_SMALL,
    UI_CSS_FONT_SIZE_MEDIUM    = UI_CSS_VALUE_MEDIUM,
    UI_CSS_FONT_SIZE_LARGE     = UI_CSS_VALUE_LARGE,
    UI_CSS_FONT_SIZE_X_LARGE   = UI_CSS_VALUE_X_LARGE,
    UI_CSS_FONT_SIZE_XX_LARGE  = UI_CSS_VALUE_XX_LARGE,
    UI_CSS_FONT_SIZE_XXX_LARGE = UI_CSS_VALUE_XXX_LARGE,
    UI_CSS_FONT_SIZE_LARGER    = UI_CSS_VALUE_LARGER,
    UI_CSS_FONT_SIZE_SMALLER   = UI_CSS_VALUE_SMALLER,
    UI_CSS_FONT_SIZE_MATH      = UI_CSS_VALUE_MATH,
    UI_CSS_FONT_SIZE__LENGTH   = UI_CSS_VALUE__LENGTH
};
typedef unsigned int ui_css_font_size_type_t;

enum {
    UI_CSS_FONT_STRETCH_NORMAL          = UI_CSS_VALUE_NORMAL,
    UI_CSS_FONT_STRETCH__PERCENTAGE     = UI_CSS_VALUE__PERCENTAGE,
    UI_CSS_FONT_STRETCH_ULTRA_CONDENSED = UI_CSS_VALUE_ULTRA_CONDENSED,
    UI_CSS_FONT_STRETCH_EXTRA_CONDENSED = UI_CSS_VALUE_EXTRA_CONDENSED,
    UI_CSS_FONT_STRETCH_CONDENSED       = UI_CSS_VALUE_CONDENSED,
    UI_CSS_FONT_STRETCH_SEMI_CONDENSED  = UI_CSS_VALUE_SEMI_CONDENSED,
    UI_CSS_FONT_STRETCH_SEMI_EXPANDED   = UI_CSS_VALUE_SEMI_EXPANDED,
    UI_CSS_FONT_STRETCH_EXPANDED        = UI_CSS_VALUE_EXPANDED,
    UI_CSS_FONT_STRETCH_EXTRA_EXPANDED  = UI_CSS_VALUE_EXTRA_EXPANDED,
    UI_CSS_FONT_STRETCH_ULTRA_EXPANDED  = UI_CSS_VALUE_ULTRA_EXPANDED
};
typedef unsigned int ui_css_font_stretch_type_t;

enum {
    UI_CSS_FONT_STYLE_NORMAL  = UI_CSS_VALUE_NORMAL,
    UI_CSS_FONT_STYLE_ITALIC  = UI_CSS_VALUE_ITALIC,
    UI_CSS_FONT_STYLE_OBLIQUE = UI_CSS_VALUE_OBLIQUE
};
typedef unsigned int ui_css_font_style_type_t;

enum {
    UI_CSS_FONT_WEIGHT_NORMAL  = UI_CSS_VALUE_NORMAL,
    UI_CSS_FONT_WEIGHT_BOLD    = UI_CSS_VALUE_BOLD,
    UI_CSS_FONT_WEIGHT__NUMBER = UI_CSS_VALUE__NUMBER,
    UI_CSS_FONT_WEIGHT_BOLDER  = UI_CSS_VALUE_BOLDER,
    UI_CSS_FONT_WEIGHT_LIGHTER = UI_CSS_VALUE_LIGHTER
};
typedef unsigned int ui_css_font_weight_type_t;

enum {
    UI_CSS_HANGING_PUNCTUATION_NONE      = UI_CSS_VALUE_NONE,
    UI_CSS_HANGING_PUNCTUATION_FIRST     = UI_CSS_VALUE_FIRST,
    UI_CSS_HANGING_PUNCTUATION_FORCE_END = UI_CSS_VALUE_FORCE_END,
    UI_CSS_HANGING_PUNCTUATION_ALLOW_END = UI_CSS_VALUE_ALLOW_END,
    UI_CSS_HANGING_PUNCTUATION_LAST      = UI_CSS_VALUE_LAST
};
typedef unsigned int ui_css_hanging_punctuation_type_t;

enum {
    UI_CSS_HEIGHT_AUTO        = UI_CSS_VALUE_AUTO,
    UI_CSS_HEIGHT_MIN_CONTENT = UI_CSS_VALUE_MIN_CONTENT,
    UI_CSS_HEIGHT_MAX_CONTENT = UI_CSS_VALUE_MAX_CONTENT,
    UI_CSS_HEIGHT__LENGTH     = UI_CSS_VALUE__LENGTH,
    UI_CSS_HEIGHT__PERCENTAGE = UI_CSS_VALUE__PERCENTAGE,
    UI_CSS_HEIGHT__NUMBER     = UI_CSS_VALUE__NUMBER,
    UI_CSS_HEIGHT__ANGLE      = UI_CSS_VALUE__ANGLE
};
typedef unsigned int ui_css_height_type_t;

enum {
    UI_CSS_HYPHENS_NONE   = UI_CSS_VALUE_NONE,
    UI_CSS_HYPHENS_MANUAL = UI_CSS_VALUE_MANUAL,
    UI_CSS_HYPHENS_AUTO   = UI_CSS_VALUE_AUTO
};
typedef unsigned int ui_css_hyphens_type_t;

enum {
    UI_CSS_INSET_BLOCK_END_AUTO        = UI_CSS_VALUE_AUTO,
    UI_CSS_INSET_BLOCK_END__LENGTH     = UI_CSS_VALUE__LENGTH,
    UI_CSS_INSET_BLOCK_END__PERCENTAGE = UI_CSS_VALUE__PERCENTAGE
};
typedef unsigned int ui_css_inset_block_end_type_t;

enum {
    UI_CSS_INSET_BLOCK_START_AUTO        = UI_CSS_VALUE_AUTO,
    UI_CSS_INSET_BLOCK_START__LENGTH     = UI_CSS_VALUE__LENGTH,
    UI_CSS_INSET_BLOCK_START__PERCENTAGE = UI_CSS_VALUE__PERCENTAGE
};
typedef unsigned int ui_css_inset_block_start_type_t;

enum {
    UI_CSS_INSET_INLINE_END_AUTO        = UI_CSS_VALUE_AUTO,
    UI_CSS_INSET_INLINE_END__LENGTH     = UI_CSS_VALUE__LENGTH,
    UI_CSS_INSET_INLINE_END__PERCENTAGE = UI_CSS_VALUE__PERCENTAGE
};
typedef unsigned int ui_css_inset_inline_end_type_t;

enum {
    UI_CSS_INSET_INLINE_START_AUTO        = UI_CSS_VALUE_AUTO,
    UI_CSS_INSET_INLINE_START__LENGTH     = UI_CSS_VALUE__LENGTH,
    UI_CSS_INSET_INLINE_START__PERCENTAGE = UI_CSS_VALUE__PERCENTAGE
};
typedef unsigned int ui_css_inset_inline_start_type_t;

enum {
    UI_CSS_JUSTIFY_CONTENT_FLEX_START    = UI_CSS_VALUE_FLEX_START,
    UI_CSS_JUSTIFY_CONTENT_FLEX_END      = UI_CSS_VALUE_FLEX_END,
    UI_CSS_JUSTIFY_CONTENT_CENTER        = UI_CSS_VALUE_CENTER,
    UI_CSS_JUSTIFY_CONTENT_SPACE_BETWEEN = UI_CSS_VALUE_SPACE_BETWEEN,
    UI_CSS_JUSTIFY_CONTENT_SPACE_AROUND  = UI_CSS_VALUE_SPACE_AROUND,
    UI_CSS_JUSTIFY_CONTENT_SPACE_EVENLY  = UI_CSS_VALUE_SPACE_EVENLY
};
typedef unsigned int ui_css_justify_content_type_t;

enum {
    UI_CSS_LEFT_AUTO        = UI_CSS_VALUE_AUTO,
    UI_CSS_LEFT__LENGTH     = UI_CSS_VALUE__LENGTH,
    UI_CSS_LEFT__PERCENTAGE = UI_CSS_VALUE__PERCENTAGE
};
typedef unsigned int ui_css_left_type_t;

enum {
    UI_CSS_LETTER_SPACING_NORMAL  = UI_CSS_VALUE_NORMAL,
    UI_CSS_LETTER_SPACING__LENGTH = UI_CSS_VALUE__LENGTH
};
typedef unsigned int ui_css_letter_spacing_type_t;

enum {
    UI_CSS_LINE_BREAK_AUTO     = UI_CSS_VALUE_AUTO,
    UI_CSS_LINE_BREAK_LOOSE    = UI_CSS_VALUE_LOOSE,
    UI_CSS_LINE_BREAK_NORMAL   = UI_CSS_VALUE_NORMAL,
    UI_CSS_LINE_BREAK_STRICT   = UI_CSS_VALUE_STRICT,
    UI_CSS_LINE_BREAK_ANYWHERE = UI_CSS_VALUE_ANYWHERE
};
typedef unsigned int ui_css_line_break_type_t;

enum {
    UI_CSS_LINE_HEIGHT_NORMAL      = UI_CSS_VALUE_NORMAL,
    UI_CSS_LINE_HEIGHT__NUMBER     = UI_CSS_VALUE__NUMBER,
    UI_CSS_LINE_HEIGHT__LENGTH     = UI_CSS_VALUE__LENGTH,
    UI_CSS_LINE_HEIGHT__PERCENTAGE = UI_CSS_VALUE__PERCENTAGE
};
typedef unsigned int ui_css_line_height_type_t;

enum {
    UI_CSS_MARGIN_AUTO        = UI_CSS_VALUE_AUTO,
    UI_CSS_MARGIN__LENGTH     = UI_CSS_VALUE__LENGTH,
    UI_CSS_MARGIN__PERCENTAGE = UI_CSS_VALUE__PERCENTAGE
};
typedef unsigned int ui_css_margin_type_t;

enum {
    UI_CSS_MARGIN_BOTTOM_AUTO        = UI_CSS_VALUE_AUTO,
    UI_CSS_MARGIN_BOTTOM__LENGTH     = UI_CSS_VALUE__LENGTH,
    UI_CSS_MARGIN_BOTTOM__PERCENTAGE = UI_CSS_VALUE__PERCENTAGE
};
typedef unsigned int ui_css_margin_bottom_type_t;

enum {
    UI_CSS_MARGIN_LEFT_AUTO        = UI_CSS_VALUE_AUTO,
    UI_CSS_MARGIN_LEFT__LENGTH     = UI_CSS_VALUE__LENGTH,
    UI_CSS_MARGIN_LEFT__PERCENTAGE = UI_CSS_VALUE__PERCENTAGE
};
typedef unsigned int ui_css_margin_left_type_t;

enum {
    UI_CSS_MARGIN_RIGHT_AUTO        = UI_CSS_VALUE_AUTO,
    UI_CSS_MARGIN_RIGHT__LENGTH     = UI_CSS_VALUE__LENGTH,
    UI_CSS_MARGIN_RIGHT__PERCENTAGE = UI_CSS_VALUE__PERCENTAGE
};
typedef unsigned int ui_css_margin_right_type_t;

enum {
    UI_CSS_MARGIN_TOP_AUTO        = UI_CSS_VALUE_AUTO,
    UI_CSS_MARGIN_TOP__LENGTH     = UI_CSS_VALUE__LENGTH,
    UI_CSS_MARGIN_TOP__PERCENTAGE = UI_CSS_VALUE__PERCENTAGE
};
typedef unsigned int ui_css_margin_top_type_t;

enum {
    UI_CSS_MAX_HEIGHT_NONE        = UI_CSS_VALUE_NONE,
    UI_CSS_MAX_HEIGHT_MIN_CONTENT = UI_CSS_VALUE_MIN_CONTENT,
    UI_CSS_MAX_HEIGHT_MAX_CONTENT = UI_CSS_VALUE_MAX_CONTENT,
    UI_CSS_MAX_HEIGHT__LENGTH     = UI_CSS_VALUE__LENGTH,
    UI_CSS_MAX_HEIGHT__PERCENTAGE = UI_CSS_VALUE__PERCENTAGE,
    UI_CSS_MAX_HEIGHT__NUMBER     = UI_CSS_VALUE__NUMBER,
    UI_CSS_MAX_HEIGHT__ANGLE      = UI_CSS_VALUE__ANGLE
};
typedef unsigned int ui_css_max_height_type_t;

enum {
    UI_CSS_MAX_WIDTH_NONE        = UI_CSS_VALUE_NONE,
    UI_CSS_MAX_WIDTH_MIN_CONTENT = UI_CSS_VALUE_MIN_CONTENT,
    UI_CSS_MAX_WIDTH_MAX_CONTENT = UI_CSS_VALUE_MAX_CONTENT,
    UI_CSS_MAX_WIDTH__LENGTH     = UI_CSS_VALUE__LENGTH,
    UI_CSS_MAX_WIDTH__PERCENTAGE = UI_CSS_VALUE__PERCENTAGE,
    UI_CSS_MAX_WIDTH__NUMBER     = UI_CSS_VALUE__NUMBER,
    UI_CSS_MAX_WIDTH__ANGLE      = UI_CSS_VALUE__ANGLE
};
typedef unsigned int ui_css_max_width_type_t;

enum {
    UI_CSS_MIN_HEIGHT_AUTO        = UI_CSS_VALUE_AUTO,
    UI_CSS_MIN_HEIGHT_MIN_CONTENT = UI_CSS_VALUE_MIN_CONTENT,
    UI_CSS_MIN_HEIGHT_MAX_CONTENT = UI_CSS_VALUE_MAX_CONTENT,
    UI_CSS_MIN_HEIGHT__LENGTH     = UI_CSS_VALUE__LENGTH,
    UI_CSS_MIN_HEIGHT__PERCENTAGE = UI_CSS_VALUE__PERCENTAGE,
    UI_CSS_MIN_HEIGHT__NUMBER     = UI_CSS_VALUE__NUMBER,
    UI_CSS_MIN_HEIGHT__ANGLE      = UI_CSS_VALUE__ANGLE
};
typedef unsigned int ui_css_min_height_type_t;

enum {
    UI_CSS_MIN_WIDTH_AUTO        = UI_CSS_VALUE_AUTO,
    UI_CSS_MIN_WIDTH_MIN_CONTENT = UI_CSS_VALUE_MIN_CONTENT,
    UI_CSS_MIN_WIDTH_MAX_CONTENT = UI_CSS_VALUE_MAX_CONTENT,
    UI_CSS_MIN_WIDTH__LENGTH     = UI_CSS_VALUE__LENGTH,
    UI_CSS_MIN_WIDTH__PERCENTAGE = UI_CSS_VALUE__PERCENTAGE,
    UI_CSS_MIN_WIDTH__NUMBER     = UI_CSS_VALUE__NUMBER,
    UI_CSS_MIN_WIDTH__ANGLE      = UI_CSS_VALUE__ANGLE
};
typedef unsigned int ui_css_min_width_type_t;

enum {
    UI_CSS_OPACITY__NUMBER     = UI_CSS_VALUE__NUMBER,
    UI_CSS_OPACITY__PERCENTAGE = UI_CSS_VALUE__PERCENTAGE
};
typedef unsigned int ui_css_opacity_type_t;

enum {
    UI_CSS_ORDER__INTEGER = UI_CSS_VALUE__INTEGER
};
typedef unsigned int ui_css_order_type_t;

enum {
    UI_CSS_OVERFLOW_BLOCK_VISIBLE = UI_CSS_VALUE_VISIBLE,
    UI_CSS_OVERFLOW_BLOCK_HIDDEN  = UI_CSS_VALUE_HIDDEN,
    UI_CSS_OVERFLOW_BLOCK_CLIP    = UI_CSS_VALUE_CLIP,
    UI_CSS_OVERFLOW_BLOCK_SCROLL  = UI_CSS_VALUE_SCROLL,
    UI_CSS_OVERFLOW_BLOCK_AUTO    = UI_CSS_VALUE_AUTO
};
typedef unsigned int ui_css_overflow_block_type_t;

enum {
    UI_CSS_OVERFLOW_INLINE_VISIBLE = UI_CSS_VALUE_VISIBLE,
    UI_CSS_OVERFLOW_INLINE_HIDDEN  = UI_CSS_VALUE_HIDDEN,
    UI_CSS_OVERFLOW_INLINE_CLIP    = UI_CSS_VALUE_CLIP,
    UI_CSS_OVERFLOW_INLINE_SCROLL  = UI_CSS_VALUE_SCROLL,
    UI_CSS_OVERFLOW_INLINE_AUTO    = UI_CSS_VALUE_AUTO
};
typedef unsigned int ui_css_overflow_inline_type_t;

enum {
    UI_CSS_OVERFLOW_WRAP_NORMAL     = UI_CSS_VALUE_NORMAL,
    UI_CSS_OVERFLOW_WRAP_BREAK_WORD = UI_CSS_VALUE_BREAK_WORD,
    UI_CSS_OVERFLOW_WRAP_ANYWHERE   = UI_CSS_VALUE_ANYWHERE
};
typedef unsigned int ui_css_overflow_wrap_type_t;

enum {
    UI_CSS_OVERFLOW_X_VISIBLE = UI_CSS_VALUE_VISIBLE,
    UI_CSS_OVERFLOW_X_HIDDEN  = UI_CSS_VALUE_HIDDEN,
    UI_CSS_OVERFLOW_X_CLIP    = UI_CSS_VALUE_CLIP,
    UI_CSS_OVERFLOW_X_SCROLL  = UI_CSS_VALUE_SCROLL,
    UI_CSS_OVERFLOW_X_AUTO    = UI_CSS_VALUE_AUTO
};
typedef unsigned int ui_css_overflow_x_type_t;

enum {
    UI_CSS_OVERFLOW_Y_VISIBLE = UI_CSS_VALUE_VISIBLE,
    UI_CSS_OVERFLOW_Y_HIDDEN  = UI_CSS_VALUE_HIDDEN,
    UI_CSS_OVERFLOW_Y_CLIP    = UI_CSS_VALUE_CLIP,
    UI_CSS_OVERFLOW_Y_SCROLL  = UI_CSS_VALUE_SCROLL,
    UI_CSS_OVERFLOW_Y_AUTO    = UI_CSS_VALUE_AUTO
};
typedef unsigned int ui_css_overflow_y_type_t;

enum {
    UI_CSS_PADDING_AUTO        = UI_CSS_VALUE_AUTO,
    UI_CSS_PADDING__LENGTH     = UI_CSS_VALUE__LENGTH,
    UI_CSS_PADDING__PERCENTAGE = UI_CSS_VALUE__PERCENTAGE
};
typedef unsigned int ui_css_padding_type_t;

enum {
    UI_CSS_PADDING_BOTTOM_AUTO        = UI_CSS_VALUE_AUTO,
    UI_CSS_PADDING_BOTTOM__LENGTH     = UI_CSS_VALUE__LENGTH,
    UI_CSS_PADDING_BOTTOM__PERCENTAGE = UI_CSS_VALUE__PERCENTAGE
};
typedef unsigned int ui_css_padding_bottom_type_t;

enum {
    UI_CSS_PADDING_LEFT_AUTO        = UI_CSS_VALUE_AUTO,
    UI_CSS_PADDING_LEFT__LENGTH     = UI_CSS_VALUE__LENGTH,
    UI_CSS_PADDING_LEFT__PERCENTAGE = UI_CSS_VALUE__PERCENTAGE
};
typedef unsigned int ui_css_padding_left_type_t;

enum {
    UI_CSS_PADDING_RIGHT_AUTO        = UI_CSS_VALUE_AUTO,
    UI_CSS_PADDING_RIGHT__LENGTH     = UI_CSS_VALUE__LENGTH,
    UI_CSS_PADDING_RIGHT__PERCENTAGE = UI_CSS_VALUE__PERCENTAGE
};
typedef unsigned int ui_css_padding_right_type_t;

enum {
    UI_CSS_PADDING_TOP_AUTO        = UI_CSS_VALUE_AUTO,
    UI_CSS_PADDING_TOP__LENGTH     = UI_CSS_VALUE__LENGTH,
    UI_CSS_PADDING_TOP__PERCENTAGE = UI_CSS_VALUE__PERCENTAGE
};
typedef unsigned int ui_css_padding_top_type_t;

enum {
    UI_CSS_POSITION_STATIC   = UI_CSS_VALUE_STATIC,
    UI_CSS_POSITION_RELATIVE = UI_CSS_VALUE_RELATIVE,
    UI_CSS_POSITION_ABSOLUTE = UI_CSS_VALUE_ABSOLUTE,
    UI_CSS_POSITION_STICKY   = UI_CSS_VALUE_STICKY,
    UI_CSS_POSITION_FIXED    = UI_CSS_VALUE_FIXED
};
typedef unsigned int ui_css_position_type_t;

enum {
    UI_CSS_RIGHT_AUTO        = UI_CSS_VALUE_AUTO,
    UI_CSS_RIGHT__LENGTH     = UI_CSS_VALUE__LENGTH,
    UI_CSS_RIGHT__PERCENTAGE = UI_CSS_VALUE__PERCENTAGE
};
typedef unsigned int ui_css_right_type_t;

enum {
    UI_CSS_TAB_SIZE__NUMBER = UI_CSS_VALUE__NUMBER,
    UI_CSS_TAB_SIZE__LENGTH = UI_CSS_VALUE__LENGTH
};
typedef unsigned int ui_css_tab_size_type_t;

enum {
    UI_CSS_TEXT_ALIGN_START        = UI_CSS_VALUE_START,
    UI_CSS_TEXT_ALIGN_END          = UI_CSS_VALUE_END,
    UI_CSS_TEXT_ALIGN_LEFT         = UI_CSS_VALUE_LEFT,
    UI_CSS_TEXT_ALIGN_RIGHT        = UI_CSS_VALUE_RIGHT,
    UI_CSS_TEXT_ALIGN_CENTER       = UI_CSS_VALUE_CENTER,
    UI_CSS_TEXT_ALIGN_JUSTIFY      = UI_CSS_VALUE_JUSTIFY,
    UI_CSS_TEXT_ALIGN_MATCH_PARENT = UI_CSS_VALUE_MATCH_PARENT,
    UI_CSS_TEXT_ALIGN_JUSTIFY_ALL  = UI_CSS_VALUE_JUSTIFY_ALL
};
typedef unsigned int ui_css_text_align_type_t;

enum {
    UI_CSS_TEXT_ALIGN_ALL_START        = UI_CSS_VALUE_START,
    UI_CSS_TEXT_ALIGN_ALL_END          = UI_CSS_VALUE_END,
    UI_CSS_TEXT_ALIGN_ALL_LEFT         = UI_CSS_VALUE_LEFT,
    UI_CSS_TEXT_ALIGN_ALL_RIGHT        = UI_CSS_VALUE_RIGHT,
    UI_CSS_TEXT_ALIGN_ALL_CENTER       = UI_CSS_VALUE_CENTER,
    UI_CSS_TEXT_ALIGN_ALL_JUSTIFY      = UI_CSS_VALUE_JUSTIFY,
    UI_CSS_TEXT_ALIGN_ALL_MATCH_PARENT = UI_CSS_VALUE_MATCH_PARENT
};
typedef unsigned int ui_css_text_align_all_type_t;

enum {
    UI_CSS_TEXT_ALIGN_LAST_AUTO         = UI_CSS_VALUE_AUTO,
    UI_CSS_TEXT_ALIGN_LAST_START        = UI_CSS_VALUE_START,
    UI_CSS_TEXT_ALIGN_LAST_END          = UI_CSS_VALUE_END,
    UI_CSS_TEXT_ALIGN_LAST_LEFT         = UI_CSS_VALUE_LEFT,
    UI_CSS_TEXT_ALIGN_LAST_RIGHT        = UI_CSS_VALUE_RIGHT,
    UI_CSS_TEXT_ALIGN_LAST_CENTER       = UI_CSS_VALUE_CENTER,
    UI_CSS_TEXT_ALIGN_LAST_JUSTIFY      = UI_CSS_VALUE_JUSTIFY,
    UI_CSS_TEXT_ALIGN_LAST_MATCH_PARENT = UI_CSS_VALUE_MATCH_PARENT
};
typedef unsigned int ui_css_text_align_last_type_t;

enum {
    UI_CSS_TEXT_COMBINE_UPRIGHT_NONE   = UI_CSS_VALUE_NONE,
    UI_CSS_TEXT_COMBINE_UPRIGHT_ALL    = UI_CSS_VALUE_ALL,
    UI_CSS_TEXT_COMBINE_UPRIGHT_DIGITS = UI_CSS_VALUE_DIGITS
};
typedef unsigned int ui_css_text_combine_upright_type_t;





enum {
    UI_CSS_TEXT_DECORATION_LINE_NONE         = UI_CSS_VALUE_NONE,
    UI_CSS_TEXT_DECORATION_LINE_UNDERLINE    = UI_CSS_VALUE_UNDERLINE,
    UI_CSS_TEXT_DECORATION_LINE_OVERLINE     = UI_CSS_VALUE_OVERLINE,
    UI_CSS_TEXT_DECORATION_LINE_LINE_THROUGH = UI_CSS_VALUE_LINE_THROUGH,
    UI_CSS_TEXT_DECORATION_LINE_BLINK        = UI_CSS_VALUE_BLINK
};
typedef unsigned int ui_css_text_decoration_line_type_t;

enum {
    UI_CSS_TEXT_DECORATION_STYLE_SOLID  = UI_CSS_VALUE_SOLID,
    UI_CSS_TEXT_DECORATION_STYLE_DOUBLE = UI_CSS_VALUE_DOUBLE,
    UI_CSS_TEXT_DECORATION_STYLE_DOTTED = UI_CSS_VALUE_DOTTED,
    UI_CSS_TEXT_DECORATION_STYLE_DASHED = UI_CSS_VALUE_DASHED,
    UI_CSS_TEXT_DECORATION_STYLE_WAVY   = UI_CSS_VALUE_WAVY
};
typedef unsigned int ui_css_text_decoration_style_type_t;

enum {
    UI_CSS_TEXT_INDENT__LENGTH     = UI_CSS_VALUE__LENGTH,
    UI_CSS_TEXT_INDENT__PERCENTAGE = UI_CSS_VALUE__PERCENTAGE,
    UI_CSS_TEXT_INDENT_HANGING     = UI_CSS_VALUE_HANGING,
    UI_CSS_TEXT_INDENT_EACH_LINE   = UI_CSS_VALUE_EACH_LINE
};
typedef unsigned int ui_css_text_indent_type_t;

enum {
    UI_CSS_TEXT_JUSTIFY_AUTO            = UI_CSS_VALUE_AUTO,
    UI_CSS_TEXT_JUSTIFY_NONE            = UI_CSS_VALUE_NONE,
    UI_CSS_TEXT_JUSTIFY_INTER_WORD      = UI_CSS_VALUE_INTER_WORD,
    UI_CSS_TEXT_JUSTIFY_INTER_CHARACTER = UI_CSS_VALUE_INTER_CHARACTER
};
typedef unsigned int ui_css_text_justify_type_t;

enum {
    UI_CSS_TEXT_ORIENTATION_MIXED    = UI_CSS_VALUE_MIXED,
    UI_CSS_TEXT_ORIENTATION_UPRIGHT  = UI_CSS_VALUE_UPRIGHT,
    UI_CSS_TEXT_ORIENTATION_SIDEWAYS = UI_CSS_VALUE_SIDEWAYS
};
typedef unsigned int ui_css_text_orientation_type_t;

enum {
    UI_CSS_TEXT_OVERFLOW_CLIP     = UI_CSS_VALUE_CLIP,
    UI_CSS_TEXT_OVERFLOW_ELLIPSIS = UI_CSS_VALUE_ELLIPSIS
};
typedef unsigned int ui_css_text_overflow_type_t;

enum {
    UI_CSS_TEXT_TRANSFORM_NONE           = UI_CSS_VALUE_NONE,
    UI_CSS_TEXT_TRANSFORM_CAPITALIZE     = UI_CSS_VALUE_CAPITALIZE,
    UI_CSS_TEXT_TRANSFORM_UPPERCASE      = UI_CSS_VALUE_UPPERCASE,
    UI_CSS_TEXT_TRANSFORM_LOWERCASE      = UI_CSS_VALUE_LOWERCASE,
    UI_CSS_TEXT_TRANSFORM_FULL_WIDTH     = UI_CSS_VALUE_FULL_WIDTH,
    UI_CSS_TEXT_TRANSFORM_FULL_SIZE_KANA = UI_CSS_VALUE_FULL_SIZE_KANA
};
typedef unsigned int ui_css_text_transform_type_t;

enum {
    UI_CSS_TOP_AUTO        = UI_CSS_VALUE_AUTO,
    UI_CSS_TOP__LENGTH     = UI_CSS_VALUE__LENGTH,
    UI_CSS_TOP__PERCENTAGE = UI_CSS_VALUE__PERCENTAGE
};
typedef unsigned int ui_css_top_type_t;

enum {
    UI_CSS_UNICODE_BIDI_NORMAL           = UI_CSS_VALUE_NORMAL,
    UI_CSS_UNICODE_BIDI_EMBED            = UI_CSS_VALUE_EMBED,
    UI_CSS_UNICODE_BIDI_ISOLATE          = UI_CSS_VALUE_ISOLATE,
    UI_CSS_UNICODE_BIDI_BIDI_OVERRIDE    = UI_CSS_VALUE_BIDI_OVERRIDE,
    UI_CSS_UNICODE_BIDI_ISOLATE_OVERRIDE = UI_CSS_VALUE_ISOLATE_OVERRIDE,
    UI_CSS_UNICODE_BIDI_PLAINTEXT        = UI_CSS_VALUE_PLAINTEXT
};
typedef unsigned int ui_css_unicode_bidi_type_t;

enum {
    UI_CSS_VERTICAL_ALIGN_FIRST = UI_CSS_VALUE_FIRST,
    UI_CSS_VERTICAL_ALIGN_LAST  = UI_CSS_VALUE_LAST
};
typedef unsigned int ui_css_vertical_align_type_t;

enum {
    UI_CSS_VISIBILITY_VISIBLE  = UI_CSS_VALUE_VISIBLE,
    UI_CSS_VISIBILITY_HIDDEN   = UI_CSS_VALUE_HIDDEN,
    UI_CSS_VISIBILITY_COLLAPSE = UI_CSS_VALUE_COLLAPSE
};
typedef unsigned int ui_css_visibility_type_t;

enum {
    UI_CSS_WHITE_SPACE_NORMAL       = UI_CSS_VALUE_NORMAL,
    UI_CSS_WHITE_SPACE_PRE          = UI_CSS_VALUE_PRE,
    UI_CSS_WHITE_SPACE_NOWRAP       = UI_CSS_VALUE_NOWRAP,
    UI_CSS_WHITE_SPACE_PRE_WRAP     = UI_CSS_VALUE_PRE_WRAP,
    UI_CSS_WHITE_SPACE_BREAK_SPACES = UI_CSS_VALUE_BREAK_SPACES,
    UI_CSS_WHITE_SPACE_PRE_LINE     = UI_CSS_VALUE_PRE_LINE
};
typedef unsigned int ui_css_white_space_type_t;

enum {
    UI_CSS_WIDTH_AUTO        = UI_CSS_VALUE_AUTO,
    UI_CSS_WIDTH_MIN_CONTENT = UI_CSS_VALUE_MIN_CONTENT,
    UI_CSS_WIDTH_MAX_CONTENT = UI_CSS_VALUE_MAX_CONTENT,
    UI_CSS_WIDTH__LENGTH     = UI_CSS_VALUE__LENGTH,
    UI_CSS_WIDTH__PERCENTAGE = UI_CSS_VALUE__PERCENTAGE,
    UI_CSS_WIDTH__NUMBER     = UI_CSS_VALUE__NUMBER,
    UI_CSS_WIDTH__ANGLE      = UI_CSS_VALUE__ANGLE
};
typedef unsigned int ui_css_width_type_t;

enum {
    UI_CSS_WORD_BREAK_NORMAL     = UI_CSS_VALUE_NORMAL,
    UI_CSS_WORD_BREAK_KEEP_ALL   = UI_CSS_VALUE_KEEP_ALL,
    UI_CSS_WORD_BREAK_BREAK_ALL  = UI_CSS_VALUE_BREAK_ALL,
    UI_CSS_WORD_BREAK_BREAK_WORD = UI_CSS_VALUE_BREAK_WORD
};
typedef unsigned int ui_css_word_break_type_t;

enum {
    UI_CSS_WORD_SPACING_NORMAL  = UI_CSS_VALUE_NORMAL,
    UI_CSS_WORD_SPACING__LENGTH = UI_CSS_VALUE__LENGTH
};
typedef unsigned int ui_css_word_spacing_type_t;

enum {
    UI_CSS_WORD_WRAP_NORMAL     = UI_CSS_VALUE_NORMAL,
    UI_CSS_WORD_WRAP_BREAK_WORD = UI_CSS_VALUE_BREAK_WORD,
    UI_CSS_WORD_WRAP_ANYWHERE   = UI_CSS_VALUE_ANYWHERE
};
typedef unsigned int ui_css_word_wrap_type_t;

enum {
    UI_CSS_WRAP_FLOW_AUTO    = UI_CSS_VALUE_AUTO,
    UI_CSS_WRAP_FLOW_BOTH    = UI_CSS_VALUE_BOTH,
    UI_CSS_WRAP_FLOW_START   = UI_CSS_VALUE_START,
    UI_CSS_WRAP_FLOW_END     = UI_CSS_VALUE_END,
    UI_CSS_WRAP_FLOW_MINIMUM = UI_CSS_VALUE_MINIMUM,
    UI_CSS_WRAP_FLOW_MAXIMUM = UI_CSS_VALUE_MAXIMUM,
    UI_CSS_WRAP_FLOW_CLEAR   = UI_CSS_VALUE_CLEAR
};
typedef unsigned int ui_css_wrap_flow_type_t;

enum {
    UI_CSS_WRAP_THROUGH_WRAP = UI_CSS_VALUE_WRAP,
    UI_CSS_WRAP_THROUGH_NONE = UI_CSS_VALUE_NONE
};
typedef unsigned int ui_css_wrap_through_type_t;

enum {
    UI_CSS_WRITING_MODE_HORIZONTAL_TB = UI_CSS_VALUE_HORIZONTAL_TB,
    UI_CSS_WRITING_MODE_VERTICAL_RL   = UI_CSS_VALUE_VERTICAL_RL,
    UI_CSS_WRITING_MODE_VERTICAL_LR   = UI_CSS_VALUE_VERTICAL_LR,
    UI_CSS_WRITING_MODE_SIDEWAYS_RL   = UI_CSS_VALUE_SIDEWAYS_RL,
    UI_CSS_WRITING_MODE_SIDEWAYS_LR   = UI_CSS_VALUE_SIDEWAYS_LR
};
typedef unsigned int ui_css_writing_mode_type_t;

enum {
    UI_CSS_Z_INDEX_AUTO     = UI_CSS_VALUE_AUTO,
    UI_CSS_Z_INDEX__INTEGER = UI_CSS_VALUE__INTEGER
};
typedef unsigned int ui_css_z_index_type_t;