cmake_minimum_required(VERSION 3.10...5.0)
project(OpenUI)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR})
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR})
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR})
set(OPENUI_SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR} CACHE STRING "OpenUI Source Path")
set(OPENUI_EXTERNAL_DIR ${CMAKE_CURRENT_SOURCE_DIR}/External CACHE STRING "OpenUI External Path")
option(OPENUI_ENABLE_SAMPLE "Enable Sample Compile" OFF)

if(MSVC)
    add_compile_options(/utf-8)
else()
    add_compile_options(-finput-charset=UTF-8)
endif()

include_directories(${OPENUI_SOURCE_DIR})
add_subdirectory(OpenVG)
add_subdirectory(OpenUI)
if(OPENUI_ENABLE_SAMPLE)
add_subdirectory(Sample)
endif()